//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace Libs.TopupPartner.PayPlusOrder
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "APIGameServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class APIGameService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback RequestTopupOperationCompleted;

        private System.Threading.SendOrPostCallback RequestByCardOperationCompleted;

        private System.Threading.SendOrPostCallback RequestTranferBalanceOperationCompleted;

        /// <remarks/>
        public APIGameService(string url)
        {
            //this.Url = "http://localhost:1588/APIGame.asmx";
            this.Url = url;
        }

        /// <remarks/>
        public event RequestTopupCompletedEventHandler RequestTopupCompleted;

        /// <remarks/>
        public event RequestByCardCompletedEventHandler RequestByCardCompleted;

        /// <remarks/>
        public event RequestTranferBalanceCompletedEventHandler RequestTranferBalanceCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestTopup", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestTopup(string transactionId, string telco, string partnerCode, string providerCode, string sim, string simTarget, string clientId, string cardSerial, string cardCode, int slot, int amount)
        {
            object[] results = this.Invoke("RequestTopup", new object[] {
                        transactionId,
                        telco,
                        partnerCode,
                        providerCode,
                        sim,
                        simTarget,
                        clientId,
                        cardSerial,
                        cardCode,
                        slot,
                        amount});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestTopup(string transactionId, string telco, string partnerCode, string providerCode, string sim, string simTarget, string clientId, string cardSerial, string cardCode, int slot, int amount, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestTopup", new object[] {
                        transactionId,
                        telco,
                        partnerCode,
                        providerCode,
                        sim,
                        simTarget,
                        clientId,
                        cardSerial,
                        cardCode,
                        slot,
                        amount}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestTopup(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestTopupAsync(string transactionId, string telco, string partnerCode, string providerCode, string sim, string simTarget, string clientId, string cardSerial, string cardCode, int slot, int amount)
        {
            this.RequestTopupAsync(transactionId, telco, partnerCode, providerCode, sim, simTarget, clientId, cardSerial, cardCode, slot, amount, null);
        }

        /// <remarks/>
        public void RequestTopupAsync(string transactionId, string telco, string partnerCode, string providerCode, string sim, string simTarget, string clientId, string cardSerial, string cardCode, int slot, int amount, object userState)
        {
            if ((this.RequestTopupOperationCompleted == null))
            {
                this.RequestTopupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestTopupOperationCompleted);
            }
            this.InvokeAsync("RequestTopup", new object[] {
                        transactionId,
                        telco,
                        partnerCode,
                        providerCode,
                        sim,
                        simTarget,
                        clientId,
                        cardSerial,
                        cardCode,
                        slot,
                        amount}, this.RequestTopupOperationCompleted, userState);
        }

        private void OnRequestTopupOperationCompleted(object arg)
        {
            if ((this.RequestTopupCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestTopupCompleted(this, new RequestTopupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestByCard", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestByCard(string transactionId, string partnerCode, string providerCode, string telco, int amount, int quantity, string clientId)
        {
            object[] results = this.Invoke("RequestByCard", new object[] {
                        transactionId,
                        partnerCode,
                        providerCode,
                        telco,
                        amount,
                        quantity,
                        clientId});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestByCard(string transactionId, string partnerCode, string providerCode, string telco, int amount, int quantity, string clientId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestByCard", new object[] {
                        transactionId,
                        partnerCode,
                        providerCode,
                        telco,
                        amount,
                        quantity,
                        clientId}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestByCard(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestByCardAsync(string transactionId, string partnerCode, string providerCode, string telco, int amount, int quantity, string clientId)
        {
            this.RequestByCardAsync(transactionId, partnerCode, providerCode, telco, amount, quantity, clientId, null);
        }

        /// <remarks/>
        public void RequestByCardAsync(string transactionId, string partnerCode, string providerCode, string telco, int amount, int quantity, string clientId, object userState)
        {
            if ((this.RequestByCardOperationCompleted == null))
            {
                this.RequestByCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestByCardOperationCompleted);
            }
            this.InvokeAsync("RequestByCard", new object[] {
                        transactionId,
                        partnerCode,
                        providerCode,
                        telco,
                        amount,
                        quantity,
                        clientId}, this.RequestByCardOperationCompleted, userState);
        }

        private void OnRequestByCardOperationCompleted(object arg)
        {
            if ((this.RequestByCardCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestByCardCompleted(this, new RequestByCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestTranferBalance", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestTranferBalance(string transactionId, string partnerCode, string providerCode, string telco, int amount, string simTarget, string clientId)
        {
            object[] results = this.Invoke("RequestTranferBalance", new object[] {
                        transactionId,
                        partnerCode,
                        providerCode,
                        telco,
                        amount,
                        simTarget,
                        clientId});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestTranferBalance(string transactionId, string partnerCode, string providerCode, string telco, int amount, string simTarget, string clientId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestTranferBalance", new object[] {
                        transactionId,
                        partnerCode,
                        providerCode,
                        telco,
                        amount,
                        simTarget,
                        clientId}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestTranferBalance(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestTranferBalanceAsync(string transactionId, string partnerCode, string providerCode, string telco, int amount, string simTarget, string clientId)
        {
            this.RequestTranferBalanceAsync(transactionId, partnerCode, providerCode, telco, amount, simTarget, clientId, null);
        }

        /// <remarks/>
        public void RequestTranferBalanceAsync(string transactionId, string partnerCode, string providerCode, string telco, int amount, string simTarget, string clientId, object userState)
        {
            if ((this.RequestTranferBalanceOperationCompleted == null))
            {
                this.RequestTranferBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestTranferBalanceOperationCompleted);
            }
            this.InvokeAsync("RequestTranferBalance", new object[] {
                        transactionId,
                        partnerCode,
                        providerCode,
                        telco,
                        amount,
                        simTarget,
                        clientId}, this.RequestTranferBalanceOperationCompleted, userState);
        }

        private void OnRequestTranferBalanceOperationCompleted(object arg)
        {
            if ((this.RequestTranferBalanceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestTranferBalanceCompleted(this, new RequestTranferBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void RequestTopupCompletedEventHandler(object sender, RequestTopupCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestTopupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestTopupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void RequestByCardCompletedEventHandler(object sender, RequestByCardCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestByCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestByCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void RequestTranferBalanceCompletedEventHandler(object sender, RequestTranferBalanceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestTranferBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestTranferBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
