//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 

namespace Libs.CardTelco
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "jamo_cardapiSoap", Namespace = "http://tempuri.org/")]
    public partial class jamo_cardapi : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback receiveChargeOperationCompleted;

        /// <remarks/>
        public jamo_cardapi(string url)
        {
            //this.Url = "http://203.162.70.37:8083/jamo_cardapi.asmx";
            this.Url = url;
        }

        /// <remarks/>
        public event receiveChargeCompletedEventHandler receiveChargeCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/receiveCharge", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string receiveCharge(string username, string card_serial, string card_code, string provider, string merchant_code)
        {
            object[] results = this.Invoke("receiveCharge", new object[] {
                    username,
                    card_serial,
                    card_code,
                    provider,
                    merchant_code});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginreceiveCharge(string username, string card_serial, string card_code, string provider, string merchant_code, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("receiveCharge", new object[] {
                    username,
                    card_serial,
                    card_code,
                    provider,
                    merchant_code}, callback, asyncState);
        }

        /// <remarks/>
        public string EndreceiveCharge(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void receiveChargeAsync(string username, string card_serial, string card_code, string provider, string merchant_code)
        {
            this.receiveChargeAsync(username, card_serial, card_code, provider, merchant_code, null);
        }

        /// <remarks/>
        public void receiveChargeAsync(string username, string card_serial, string card_code, string provider, string merchant_code, object userState)
        {
            if ((this.receiveChargeOperationCompleted == null))
            {
                this.receiveChargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveChargeOperationCompleted);
            }
            this.InvokeAsync("receiveCharge", new object[] {
                    username,
                    card_serial,
                    card_code,
                    provider,
                    merchant_code}, this.receiveChargeOperationCompleted, userState);
        }

        private void OnreceiveChargeOperationCompleted(object arg)
        {
            if ((this.receiveChargeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveChargeCompleted(this, new receiveChargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void receiveChargeCompletedEventHandler(object sender, receiveChargeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveChargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal receiveChargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}