//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


namespace Libs.BankDirect.Banknet
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "DirectPaymentSoap11Binding", Namespace = "http://pgWebservices")]
    public partial class DirectPayment : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback QuerryBillStatusOperationCompleted;

        private System.Threading.SendOrPostCallback ConfirmTransactionResultOperationCompleted;

        private System.Threading.SendOrPostCallback checkCardHolderOperationCompleted;

        private System.Threading.SendOrPostCallback SendGoodInfo_ExtOperationCompleted;

        private System.Threading.SendOrPostCallback verifyOTPOperationCompleted;

        /// <remarks/>
        public DirectPayment(string url)
        {
            this.Url = url;
            //this.Url = "http://sandbox.bndebit.vn/pg2705/services/DirectPayment.DirectPaymentHttpSoap11En" + "dpoint";
        }

        /// <remarks/>
        public event QuerryBillStatusCompletedEventHandler QuerryBillStatusCompleted;

        /// <remarks/>
        public event ConfirmTransactionResultCompletedEventHandler ConfirmTransactionResultCompleted;

        /// <remarks/>
        public event checkCardHolderCompletedEventHandler checkCardHolderCompleted;

        /// <remarks/>
        public event SendGoodInfo_ExtCompletedEventHandler SendGoodInfo_ExtCompleted;

        /// <remarks/>
        public event verifyOTPCompletedEventHandler verifyOTPCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QuerryBillStatus", RequestNamespace = "http://pgWebservices", ResponseNamespace = "http://pgWebservices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
        public string QuerryBillStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_secure_code)
        {
            object[] results = this.Invoke("QuerryBillStatus", new object[] {
                    merchant_trans_id,
                    trans_id,
                    merchant_code,
                    trans_secure_code});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginQuerryBillStatus(string merchant_trans_id, string trans_id, string merchant_code, string trans_secure_code, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("QuerryBillStatus", new object[] {
                    merchant_trans_id,
                    trans_id,
                    merchant_code,
                    trans_secure_code}, callback, asyncState);
        }

        /// <remarks/>
        public string EndQuerryBillStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void QuerryBillStatusAsync(string merchant_trans_id, string trans_id, string merchant_code, string trans_secure_code)
        {
            this.QuerryBillStatusAsync(merchant_trans_id, trans_id, merchant_code, trans_secure_code, null);
        }

        /// <remarks/>
        public void QuerryBillStatusAsync(string merchant_trans_id, string trans_id, string merchant_code, string trans_secure_code, object userState)
        {
            if ((this.QuerryBillStatusOperationCompleted == null))
            {
                this.QuerryBillStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerryBillStatusOperationCompleted);
            }
            this.InvokeAsync("QuerryBillStatus", new object[] {
                    merchant_trans_id,
                    trans_id,
                    merchant_code,
                    trans_secure_code}, this.QuerryBillStatusOperationCompleted, userState);
        }

        private void OnQuerryBillStatusOperationCompleted(object arg)
        {
            if ((this.QuerryBillStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerryBillStatusCompleted(this, new QuerryBillStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ConfirmTransactionResult", RequestNamespace = "http://pgWebservices", ResponseNamespace = "http://pgWebservices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
        public string ConfirmTransactionResult([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_result, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_secure_code)
        {
            object[] results = this.Invoke("ConfirmTransactionResult", new object[] {
                    merchant_trans_id,
                    trans_id,
                    merchant_code,
                    trans_result,
                    trans_secure_code});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConfirmTransactionResult(string merchant_trans_id, string trans_id, string merchant_code, string trans_result, string trans_secure_code, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConfirmTransactionResult", new object[] {
                    merchant_trans_id,
                    trans_id,
                    merchant_code,
                    trans_result,
                    trans_secure_code}, callback, asyncState);
        }

        /// <remarks/>
        public string EndConfirmTransactionResult(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ConfirmTransactionResultAsync(string merchant_trans_id, string trans_id, string merchant_code, string trans_result, string trans_secure_code)
        {
            this.ConfirmTransactionResultAsync(merchant_trans_id, trans_id, merchant_code, trans_result, trans_secure_code, null);
        }

        /// <remarks/>
        public void ConfirmTransactionResultAsync(string merchant_trans_id, string trans_id, string merchant_code, string trans_result, string trans_secure_code, object userState)
        {
            if ((this.ConfirmTransactionResultOperationCompleted == null))
            {
                this.ConfirmTransactionResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmTransactionResultOperationCompleted);
            }
            this.InvokeAsync("ConfirmTransactionResult", new object[] {
                    merchant_trans_id,
                    trans_id,
                    merchant_code,
                    trans_result,
                    trans_secure_code}, this.ConfirmTransactionResultOperationCompleted, userState);
        }

        private void OnConfirmTransactionResultOperationCompleted(object arg)
        {
            if ((this.ConfirmTransactionResultCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmTransactionResultCompleted(this, new ConfirmTransactionResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:checkCardHolder", RequestNamespace = "http://pgWebservices", ResponseNamespace = "http://pgWebservices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
        public string checkCardHolder([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string card_holder_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string card_holder_name, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string card_holder_month, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string card_holder_year, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string otpGetType, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_secure_code)
        {
            object[] results = this.Invoke("checkCardHolder", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    trans_id,
                    card_holder_number,
                    card_holder_name,
                    card_holder_month,
                    card_holder_year,
                    otpGetType,
                    trans_secure_code});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegincheckCardHolder(string merchant_trans_id, string merchant_code, string trans_id, string card_holder_number, string card_holder_name, string card_holder_month, string card_holder_year, string otpGetType, string trans_secure_code, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("checkCardHolder", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    trans_id,
                    card_holder_number,
                    card_holder_name,
                    card_holder_month,
                    card_holder_year,
                    otpGetType,
                    trans_secure_code}, callback, asyncState);
        }

        /// <remarks/>
        public string EndcheckCardHolder(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void checkCardHolderAsync(string merchant_trans_id, string merchant_code, string trans_id, string card_holder_number, string card_holder_name, string card_holder_month, string card_holder_year, string otpGetType, string trans_secure_code)
        {
            this.checkCardHolderAsync(merchant_trans_id, merchant_code, trans_id, card_holder_number, card_holder_name, card_holder_month, card_holder_year, otpGetType, trans_secure_code, null);
        }

        /// <remarks/>
        public void checkCardHolderAsync(string merchant_trans_id, string merchant_code, string trans_id, string card_holder_number, string card_holder_name, string card_holder_month, string card_holder_year, string otpGetType, string trans_secure_code, object userState)
        {
            if ((this.checkCardHolderOperationCompleted == null))
            {
                this.checkCardHolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckCardHolderOperationCompleted);
            }
            this.InvokeAsync("checkCardHolder", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    trans_id,
                    card_holder_number,
                    card_holder_name,
                    card_holder_month,
                    card_holder_year,
                    otpGetType,
                    trans_secure_code}, this.checkCardHolderOperationCompleted, userState);
        }

        private void OncheckCardHolderOperationCompleted(object arg)
        {
            if ((this.checkCardHolderCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkCardHolderCompleted(this, new checkCardHolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:SendGoodInfo_Ext", RequestNamespace = "http://pgWebservices", ResponseNamespace = "http://pgWebservices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
        public string SendGoodInfo_Ext([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string country_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string good_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string xml_description, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string net_cost, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string ship_fee, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string tax, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_datetime, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_secure_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string selected_bank)
        {
            object[] results = this.Invoke("SendGoodInfo_Ext", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    country_code,
                    good_code,
                    xml_description,
                    net_cost,
                    ship_fee,
                    tax,
                    trans_datetime,
                    trans_secure_code,
                    selected_bank});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSendGoodInfo_Ext(string merchant_trans_id, string merchant_code, string country_code, string good_code, string xml_description, string net_cost, string ship_fee, string tax, string trans_datetime, string trans_secure_code, string selected_bank, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SendGoodInfo_Ext", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    country_code,
                    good_code,
                    xml_description,
                    net_cost,
                    ship_fee,
                    tax,
                    trans_datetime,
                    trans_secure_code,
                    selected_bank}, callback, asyncState);
        }

        /// <remarks/>
        public string EndSendGoodInfo_Ext(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void SendGoodInfo_ExtAsync(string merchant_trans_id, string merchant_code, string country_code, string good_code, string xml_description, string net_cost, string ship_fee, string tax, string trans_datetime, string trans_secure_code, string selected_bank)
        {
            this.SendGoodInfo_ExtAsync(merchant_trans_id, merchant_code, country_code, good_code, xml_description, net_cost, ship_fee, tax, trans_datetime, trans_secure_code, selected_bank, null);
        }

        /// <remarks/>
        public void SendGoodInfo_ExtAsync(string merchant_trans_id, string merchant_code, string country_code, string good_code, string xml_description, string net_cost, string ship_fee, string tax, string trans_datetime, string trans_secure_code, string selected_bank, object userState)
        {
            if ((this.SendGoodInfo_ExtOperationCompleted == null))
            {
                this.SendGoodInfo_ExtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendGoodInfo_ExtOperationCompleted);
            }
            this.InvokeAsync("SendGoodInfo_Ext", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    country_code,
                    good_code,
                    xml_description,
                    net_cost,
                    ship_fee,
                    tax,
                    trans_datetime,
                    trans_secure_code,
                    selected_bank}, this.SendGoodInfo_ExtOperationCompleted, userState);
        }

        private void OnSendGoodInfo_ExtOperationCompleted(object arg)
        {
            if ((this.SendGoodInfo_ExtCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendGoodInfo_ExtCompleted(this, new SendGoodInfo_ExtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:verifyOTP", RequestNamespace = "http://pgWebservices", ResponseNamespace = "http://pgWebservices", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
        public string verifyOTP([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_id, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string otp_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string trans_secure_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string otpGetType)
        {
            object[] results = this.Invoke("verifyOTP", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    trans_id,
                    otp_code,
                    trans_secure_code,
                    otpGetType});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginverifyOTP(string merchant_trans_id, string merchant_code, string trans_id, string otp_code, string trans_secure_code, string otpGetType, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("verifyOTP", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    trans_id,
                    otp_code,
                    trans_secure_code,
                    otpGetType}, callback, asyncState);
        }

        /// <remarks/>
        public string EndverifyOTP(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void verifyOTPAsync(string merchant_trans_id, string merchant_code, string trans_id, string otp_code, string trans_secure_code, string otpGetType)
        {
            this.verifyOTPAsync(merchant_trans_id, merchant_code, trans_id, otp_code, trans_secure_code, otpGetType, null);
        }

        /// <remarks/>
        public void verifyOTPAsync(string merchant_trans_id, string merchant_code, string trans_id, string otp_code, string trans_secure_code, string otpGetType, object userState)
        {
            if ((this.verifyOTPOperationCompleted == null))
            {
                this.verifyOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyOTPOperationCompleted);
            }
            this.InvokeAsync("verifyOTP", new object[] {
                    merchant_trans_id,
                    merchant_code,
                    trans_id,
                    otp_code,
                    trans_secure_code,
                    otpGetType}, this.verifyOTPOperationCompleted, userState);
        }

        private void OnverifyOTPOperationCompleted(object arg)
        {
            if ((this.verifyOTPCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyOTPCompleted(this, new verifyOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void QuerryBillStatusCompletedEventHandler(object sender, QuerryBillStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerryBillStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal QuerryBillStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void ConfirmTransactionResultCompletedEventHandler(object sender, ConfirmTransactionResultCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmTransactionResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConfirmTransactionResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void checkCardHolderCompletedEventHandler(object sender, checkCardHolderCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkCardHolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal checkCardHolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void SendGoodInfo_ExtCompletedEventHandler(object sender, SendGoodInfo_ExtCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendGoodInfo_ExtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SendGoodInfo_ExtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void verifyOTPCompletedEventHandler(object sender, verifyOTPCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal verifyOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}