//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace Libs.CardTelco.C2C.KHD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CardToCashSoapBinding", Namespace="http://exchange.partner.service.itel.vn")]
    public partial class CardToCashService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback exchangeCardOperationCompleted;
        
        /// <remarks/>
        public CardToCashService(string url) {
            //this.Url = "http://itelservice.vn:8888/ITelService/services/CardToCash";
            this.Url = url;
        }
        
        /// <remarks/>
        public event checkTransactionCompletedEventHandler checkTransactionCompleted;
        
        /// <remarks/>
        public event exchangeCardCompletedEventHandler exchangeCardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://exchange.partner.service.itel.vn", ResponseNamespace="http://exchange.partner.service.itel.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkTransactionReturn")]
        public string checkTransaction(string input) {
            object[] results = this.Invoke("checkTransaction", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckTransaction(string input, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkTransaction", new object[] {
                        input}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckTransaction(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkTransactionAsync(string input) {
            this.checkTransactionAsync(input, null);
        }
        
        /// <remarks/>
        public void checkTransactionAsync(string input, object userState) {
            if ((this.checkTransactionOperationCompleted == null)) {
                this.checkTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckTransactionOperationCompleted);
            }
            this.InvokeAsync("checkTransaction", new object[] {
                        input}, this.checkTransactionOperationCompleted, userState);
        }
        
        private void OncheckTransactionOperationCompleted(object arg) {
            if ((this.checkTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkTransactionCompleted(this, new checkTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://exchange.partner.service.itel.vn", ResponseNamespace="http://exchange.partner.service.itel.vn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("exchangeCardReturn")]
        public string exchangeCard(string input) {
            object[] results = this.Invoke("exchangeCard", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexchangeCard(string input, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exchangeCard", new object[] {
                        input}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexchangeCard(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void exchangeCardAsync(string input) {
            this.exchangeCardAsync(input, null);
        }
        
        /// <remarks/>
        public void exchangeCardAsync(string input, object userState) {
            if ((this.exchangeCardOperationCompleted == null)) {
                this.exchangeCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexchangeCardOperationCompleted);
            }
            this.InvokeAsync("exchangeCard", new object[] {
                        input}, this.exchangeCardOperationCompleted, userState);
        }
        
        private void OnexchangeCardOperationCompleted(object arg) {
            if ((this.exchangeCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exchangeCardCompleted(this, new exchangeCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void checkTransactionCompletedEventHandler(object sender, checkTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void exchangeCardCompletedEventHandler(object sender, exchangeCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exchangeCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exchangeCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
