//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace Libs.TopupPartner.Gate {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSoap", Namespace="http://tempuri.org/")]
    public partial class ws : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuyCardJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuyCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuyCardJsonV2OperationCompleted;
        
        /// <remarks/>
        public ws(string url) {
            //this.Url = "https://daily.gate.vn/api/multicard/ws.asmx";
            this.Url = url;
        }
        
        /// <remarks/>
        public event BuyCardJsonCompletedEventHandler BuyCardJsonCompleted;
        
        /// <remarks/>
        public event BuyCardCompletedEventHandler BuyCardCompleted;
        
        /// <remarks/>
        public event CheckStockCompletedEventHandler CheckStockCompleted;
        
        /// <remarks/>
        public event CheckBalanceCompletedEventHandler CheckBalanceCompleted;
        
        /// <remarks/>
        public event BuyCardJsonV2CompletedEventHandler BuyCardJsonV2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuyCardJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuyCardJson(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID) {
            object[] results = this.Invoke("BuyCardJson", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        partnerTransID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBuyCardJson(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BuyCardJson", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        partnerTransID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndBuyCardJson(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuyCardJsonAsync(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID) {
            this.BuyCardJsonAsync(username, password, cardName, amount, quantity, partnerTransID, null);
        }
        
        /// <remarks/>
        public void BuyCardJsonAsync(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID, object userState) {
            if ((this.BuyCardJsonOperationCompleted == null)) {
                this.BuyCardJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyCardJsonOperationCompleted);
            }
            this.InvokeAsync("BuyCardJson", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        partnerTransID}, this.BuyCardJsonOperationCompleted, userState);
        }
        
        private void OnBuyCardJsonOperationCompleted(object arg) {
            if ((this.BuyCardJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyCardJsonCompleted(this, new BuyCardJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuyCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuyCard(string username, string password, string cardName, decimal amount, int quantity, ref int returnCode, ref string message, ref decimal balance, ref string transID, string partnerTransID) {
            object[] results = this.Invoke("BuyCard", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        returnCode,
                        message,
                        balance,
                        transID,
                        partnerTransID});
            returnCode = ((int)(results[1]));
            message = ((string)(results[2]));
            balance = ((decimal)(results[3]));
            transID = ((string)(results[4]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBuyCard(string username, string password, string cardName, decimal amount, int quantity, int returnCode, string message, decimal balance, string transID, string partnerTransID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BuyCard", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        returnCode,
                        message,
                        balance,
                        transID,
                        partnerTransID}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndBuyCard(System.IAsyncResult asyncResult, out int returnCode, out string message, out decimal balance, out string transID) {
            object[] results = this.EndInvoke(asyncResult);
            returnCode = ((int)(results[1]));
            message = ((string)(results[2]));
            balance = ((decimal)(results[3]));
            transID = ((string)(results[4]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuyCardAsync(string username, string password, string cardName, decimal amount, int quantity, int returnCode, string message, decimal balance, string transID, string partnerTransID) {
            this.BuyCardAsync(username, password, cardName, amount, quantity, returnCode, message, balance, transID, partnerTransID, null);
        }
        
        /// <remarks/>
        public void BuyCardAsync(string username, string password, string cardName, decimal amount, int quantity, int returnCode, string message, decimal balance, string transID, string partnerTransID, object userState) {
            if ((this.BuyCardOperationCompleted == null)) {
                this.BuyCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyCardOperationCompleted);
            }
            this.InvokeAsync("BuyCard", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        returnCode,
                        message,
                        balance,
                        transID,
                        partnerTransID}, this.BuyCardOperationCompleted, userState);
        }
        
        private void OnBuyCardOperationCompleted(object arg) {
            if ((this.BuyCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyCardCompleted(this, new BuyCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckStock(string username, string password, string cardName, decimal amount, int quarity) {
            object[] results = this.Invoke("CheckStock", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quarity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckStock(string username, string password, string cardName, decimal amount, int quarity, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckStock", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quarity}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckStock(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckStockAsync(string username, string password, string cardName, decimal amount, int quarity) {
            this.CheckStockAsync(username, password, cardName, amount, quarity, null);
        }
        
        /// <remarks/>
        public void CheckStockAsync(string username, string password, string cardName, decimal amount, int quarity, object userState) {
            if ((this.CheckStockOperationCompleted == null)) {
                this.CheckStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckStockOperationCompleted);
            }
            this.InvokeAsync("CheckStock", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quarity}, this.CheckStockOperationCompleted, userState);
        }
        
        private void OnCheckStockOperationCompleted(object arg) {
            if ((this.CheckStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckStockCompleted(this, new CheckStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckBalance(string username, string password) {
            object[] results = this.Invoke("CheckBalance", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckBalance(string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckBalance", new object[] {
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckBalance(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBalanceAsync(string username, string password) {
            this.CheckBalanceAsync(username, password, null);
        }
        
        /// <remarks/>
        public void CheckBalanceAsync(string username, string password, object userState) {
            if ((this.CheckBalanceOperationCompleted == null)) {
                this.CheckBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBalanceOperationCompleted);
            }
            this.InvokeAsync("CheckBalance", new object[] {
                        username,
                        password}, this.CheckBalanceOperationCompleted, userState);
        }
        
        private void OnCheckBalanceOperationCompleted(object arg) {
            if ((this.CheckBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBalanceCompleted(this, new CheckBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuyCardJsonV2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuyCardJsonV2(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID) {
            object[] results = this.Invoke("BuyCardJsonV2", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        partnerTransID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBuyCardJsonV2(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BuyCardJsonV2", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        partnerTransID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndBuyCardJsonV2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuyCardJsonV2Async(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID) {
            this.BuyCardJsonV2Async(username, password, cardName, amount, quantity, partnerTransID, null);
        }
        
        /// <remarks/>
        public void BuyCardJsonV2Async(string username, string password, string cardName, decimal amount, int quantity, string partnerTransID, object userState) {
            if ((this.BuyCardJsonV2OperationCompleted == null)) {
                this.BuyCardJsonV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyCardJsonV2OperationCompleted);
            }
            this.InvokeAsync("BuyCardJsonV2", new object[] {
                        username,
                        password,
                        cardName,
                        amount,
                        quantity,
                        partnerTransID}, this.BuyCardJsonV2OperationCompleted, userState);
        }
        
        private void OnBuyCardJsonV2OperationCompleted(object arg) {
            if ((this.BuyCardJsonV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyCardJsonV2Completed(this, new BuyCardJsonV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void BuyCardJsonCompletedEventHandler(object sender, BuyCardJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyCardJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuyCardJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void BuyCardCompletedEventHandler(object sender, BuyCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuyCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int returnCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public decimal balance {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string transID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void CheckStockCompletedEventHandler(object sender, CheckStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void CheckBalanceCompletedEventHandler(object sender, CheckBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void BuyCardJsonV2CompletedEventHandler(object sender, BuyCardJsonV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyCardJsonV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuyCardJsonV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
