//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.18020.
// 

namespace Libs.CardTelco.Gate.CHD
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "IgateRouteBinding", Namespace = "http://ws/")]
    public partial class IgateRouteService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ProcessRequestOperationCompleted;

        /// <remarks/>
        public IgateRouteService(string url)
        {
            //this.Url = "https://ops.gate.vn:8888/Igate_WS/Route";
            this.Url = url;
        }

        /// <remarks/>
        public event ProcessRequestCompletedEventHandler ProcessRequestCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://ws/",
            ResponseNamespace = "http://ws/", Use = System.Web.Services.Description.SoapBindingUse.Literal,
            ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return:
            System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcessRequest(
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string
                arg0,
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string
                arg1)
        {
            object[] results = this.Invoke("ProcessRequest", new object[]
            {
                arg0,
                arg1
            });
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginProcessRequest(string arg0, string arg1, System.AsyncCallback callback,
            object asyncState)
        {
            return this.BeginInvoke("ProcessRequest", new object[]
            {
                arg0,
                arg1
            }, callback, asyncState);
        }

        /// <remarks/>
        public string EndProcessRequest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ProcessRequestAsync(string arg0, string arg1)
        {
            this.ProcessRequestAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void ProcessRequestAsync(string arg0, string arg1, object userState)
        {
            if ((this.ProcessRequestOperationCompleted == null))
            {
                this.ProcessRequestOperationCompleted =
                    new System.Threading.SendOrPostCallback(this.OnProcessRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessRequest", new object[]
            {
                arg0,
                arg1
            }, this.ProcessRequestOperationCompleted, userState);
        }

        private void OnProcessRequestOperationCompleted(object arg)
        {
            if ((this.ProcessRequestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs =
                    ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessRequestCompleted(this,
                    new ProcessRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled,
                        invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    public delegate void ProcessRequestCompletedEventHandler(object sender, ProcessRequestCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ProcessRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled,
            object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}