//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace APIProxy.VTTService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CheckCardSoap", Namespace = "http://tempuri.org/")]
    public partial class CheckCard : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CheckSerialOperationCompleted;

        /// <remarks/>
        public CheckCard(string url)
        {
            //this.Url = "http://localhost:62299/CheckCard.asmx";
            this.Url = url;
        }

        /// <remarks/>
        public event CheckSerialCompletedEventHandler CheckSerialCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckSerial", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckSerial(string serial, string sign)
        {
            object[] results = this.Invoke("CheckSerial", new object[] {
                        serial,
                        sign});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCheckSerial(string serial, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CheckSerial", new object[] {
                        serial,
                        sign}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCheckSerial(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CheckSerialAsync(string serial, string sign)
        {
            this.CheckSerialAsync(serial, sign, null);
        }

        /// <remarks/>
        public void CheckSerialAsync(string serial, string sign, object userState)
        {
            if ((this.CheckSerialOperationCompleted == null))
            {
                this.CheckSerialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSerialOperationCompleted);
            }
            this.InvokeAsync("CheckSerial", new object[] {
                        serial,
                        sign}, this.CheckSerialOperationCompleted, userState);
        }

        private void OnCheckSerialOperationCompleted(object arg)
        {
            if ((this.CheckSerialCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSerialCompleted(this, new CheckSerialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void CheckSerialCompletedEventHandler(object sender, CheckSerialCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSerialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CheckSerialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

   
}
