//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace Libs.CardTelco.Gate.KHD
{
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "wsSoap", Namespace = "http://tempuri.org/")]
    public partial class ws : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ChargeCardOperationCompleted;

        /// <remarks/>
        public ws(string url)
        {
            //this.Url = "https://daily.gate.vn/api/card/ws.asmx";
            this.Url = url;
        }

        /// <remarks/>
        public event ChargeCardCompletedEventHandler ChargeCardCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChargeCard", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChargeCard(string username, string password, string serial, string pincode, string cardname, string timestamp, string signature, string partnerTransID)
        {
            object[] results = this.Invoke("ChargeCard", new object[] {
                        username,
                        password,
                        serial,
                        pincode,
                        cardname,
                        timestamp,
                        signature,
                        partnerTransID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginChargeCard(string username, string password, string serial, string pincode, string cardname, string timestamp, string signature, string partnerTransID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ChargeCard", new object[] {
                        username,
                        password,
                        serial,
                        pincode,
                        cardname,
                        timestamp,
                        signature,
                        partnerTransID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndChargeCard(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ChargeCardAsync(string username, string password, string serial, string pincode, string cardname, string timestamp, string signature, string partnerTransID)
        {
            this.ChargeCardAsync(username, password, serial, pincode, cardname, timestamp, signature, partnerTransID, null);
        }

        /// <remarks/>
        public void ChargeCardAsync(string username, string password, string serial, string pincode, string cardname, string timestamp, string signature, string partnerTransID, object userState)
        {
            if ((this.ChargeCardOperationCompleted == null))
            {
                this.ChargeCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChargeCardOperationCompleted);
            }
            this.InvokeAsync("ChargeCard", new object[] {
                        username,
                        password,
                        serial,
                        pincode,
                        cardname,
                        timestamp,
                        signature,
                        partnerTransID}, this.ChargeCardOperationCompleted, userState);
        }

        private void OnChargeCardOperationCompleted(object arg)
        {
            if ((this.ChargeCardCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChargeCardCompleted(this, new ChargeCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ChargeCardCompletedEventHandler(object sender, ChargeCardCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChargeCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ChargeCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
