//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


namespace Libs.BankGate
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "VGGBillingSoap", Namespace = "http://tempuri.org/")]
    public partial class VGGBilling : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ProcessBankGateRequestOperationCompleted;

        /// <remarks/>
        public VGGBilling(string url)
        {
            //this.Url = "http://api.sandbox.vgg.vn/VGGInternal/VGGBilling.asmx";
            this.Url = url;
        }

        /// <remarks/>
        public event ProcessBankGateRequestCompletedEventHandler ProcessBankGateRequestCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessBankGateRequest", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProcessBankGateRequest(string partnerKey, string orderNo, int status, string responseNo, string responseTime, string signature, string bankCode, int totalAmount, string fullName, string mobile)
        {
            object[] results = this.Invoke("ProcessBankGateRequest", new object[] {
                    partnerKey,
                    orderNo,
                    status,
                    responseNo,
                    responseTime,
                    signature,
                    bankCode,
                    totalAmount,
                    fullName,
                    mobile});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginProcessBankGateRequest(string partnerKey, string orderNo, int status, string responseNo, string responseTime, string signature, string bankCode, int totalAmount, string fullName, string mobile, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ProcessBankGateRequest", new object[] {
                    partnerKey,
                    orderNo,
                    status,
                    responseNo,
                    responseTime,
                    signature,
                    bankCode,
                    totalAmount,
                    fullName,
                    mobile}, callback, asyncState);
        }

        /// <remarks/>
        public int EndProcessBankGateRequest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void ProcessBankGateRequestAsync(string partnerKey, string orderNo, int status, string responseNo, string responseTime, string signature, string bankCode, int totalAmount, string fullName, string mobile)
        {
            this.ProcessBankGateRequestAsync(partnerKey, orderNo, status, responseNo, responseTime, signature, bankCode, totalAmount, fullName, mobile, null);
        }

        /// <remarks/>
        public void ProcessBankGateRequestAsync(string partnerKey, string orderNo, int status, string responseNo, string responseTime, string signature, string bankCode, int totalAmount, string fullName, string mobile, object userState)
        {
            if ((this.ProcessBankGateRequestOperationCompleted == null))
            {
                this.ProcessBankGateRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessBankGateRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessBankGateRequest", new object[] {
                    partnerKey,
                    orderNo,
                    status,
                    responseNo,
                    responseTime,
                    signature,
                    bankCode,
                    totalAmount,
                    fullName,
                    mobile}, this.ProcessBankGateRequestOperationCompleted, userState);
        }

        private void OnProcessBankGateRequestOperationCompleted(object arg)
        {
            if ((this.ProcessBankGateRequestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessBankGateRequestCompleted(this, new ProcessBankGateRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void ProcessBankGateRequestCompletedEventHandler(object sender, ProcessBankGateRequestCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessBankGateRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ProcessBankGateRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}