//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IZISoft.IMediaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.itopup.vnptepay.vn", ConfigurationName="IMediaService.TopupInterface")]
    public interface TopupInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signOutReturn")]
        IZISoft.IMediaService.SignOutResult signOut(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signOutReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.SignOutResult> signOutAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkConnectionReturn")]
        string checkConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkConnectionReturn")]
        System.Threading.Tasks.Task<string> checkConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="queryBalanceReturn")]
        IZISoft.IMediaService.BalanceResult queryBalance(string username, string requestID, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="queryBalanceReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.BalanceResult> queryBalanceAsync(string username, string requestID, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signInAsPartnerReturn")]
        IZISoft.IMediaService.SignInResult signInAsPartner(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signInAsPartnerReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.SignInResult> signInAsPartnerAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkPhoneNumberReturn")]
        bool checkPhoneNumber(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkPhoneNumberReturn")]
        System.Threading.Tasks.Task<bool> checkPhoneNumberAsync(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkTargetAccountReturn")]
        IZISoft.IMediaService.CheckTargetObject checkTargetAccount(string username, string session, string targetAcount, string providerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkTargetAccountReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.CheckTargetObject> checkTargetAccountAsync(string username, string session, string targetAcount, string providerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListCategoriesReturn")]
        IZISoft.IMediaService.CategoryListObject partnerGetListCategories(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListCategoriesReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.CategoryListObject> partnerGetListCategoriesAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListProviderOfCategoryReturn")]
        IZISoft.IMediaService.ProviderListObject partnerGetListProviderOfCategory(string username, int categoryId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListProviderOfCategoryReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.ProviderListObject> partnerGetListProviderOfCategoryAsync(string username, int categoryId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListProductOfCategoryServiceProviderReturn")]
        IZISoft.IMediaService.ProductListObject partnerGetListProductOfCategoryServiceProvider(string username, int categoryId, int providerId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListProductOfCategoryServiceProviderReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.ProductListObject> partnerGetListProductOfCategoryServiceProviderAsync(string username, int categoryId, int providerId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getListValueLevelsReturn")]
        IZISoft.IMediaService.LevelResult getListValueLevels(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getListValueLevelsReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.LevelResult> getListValueLevelsAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getProductInformationReturn")]
        IZISoft.IMediaService.ProductInfo getProductInformation(string username, int productID, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getProductInformationReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.ProductInfo> getProductInformationAsync(string username, int productID, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerCheckProductReturn")]
        IZISoft.IMediaService.CheckProducts[] partnerCheckProduct(string username, string token, int categoryId, int providerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerCheckProductReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.CheckProducts[]> partnerCheckProductAsync(string username, string token, int categoryId, int providerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerCheckProductDetailReturn")]
        IZISoft.IMediaService.CheckProductsDetail[] partnerCheckProductDetail(string username, string token, IZISoft.IMediaService.CheckProductsDetail[] checkProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerCheckProductDetailReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.CheckProductsDetail[]> partnerCheckProductDetailAsync(string username, string token, IZISoft.IMediaService.CheckProductsDetail[] checkProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerChangePasswordReturn")]
        IZISoft.IMediaService.ChangePasswordResult partnerChangePassword(string username, string oldPassword, string newPassword, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerChangePasswordReturn")]
        System.Threading.Tasks.Task<IZISoft.IMediaService.ChangePasswordResult> partnerChangePasswordAsync(string username, string oldPassword, string newPassword, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="requestHandleReturn")]
        string requestHandle(string requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="requestHandleReturn")]
        System.Threading.Tasks.Task<string> requestHandleAsync(string requestData);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class SignOutResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ChangePasswordResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CheckProductsDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private int productIdField;
        
        private int quantityField;
        
        private bool statusField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CheckProducts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private int productIdField;
        
        private string productNameField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private int productIDField;
        
        private byte[] productLogoField;
        
        private string productMessageField;
        
        private string productNameField;
        
        private int productValueField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        public int productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("productID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] productLogo {
            get {
                return this.productLogoField;
            }
            set {
                this.productLogoField = value;
                this.RaisePropertyChanged("productLogo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productMessage {
            get {
                return this.productMessageField;
            }
            set {
                this.productMessageField = value;
                this.RaisePropertyChanged("productMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        public int productValue {
            get {
                return this.productValueField;
            }
            set {
                this.productValueField = value;
                this.RaisePropertyChanged("productValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class LevelResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int[] dataValueField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public int[] dataValue {
            get {
                return this.dataValueField;
            }
            set {
                this.dataValueField = value;
                this.RaisePropertyChanged("dataValue");
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProductObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIdField;
        
        private string productNameField;
        
        private int productValueField;
        
        /// <remarks/>
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        public int productValue {
            get {
                return this.productValueField;
            }
            set {
                this.productValueField = value;
                this.RaisePropertyChanged("productValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProductListObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private ProductObject[] productListField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ProductObject[] productList {
            get {
                return this.productListField;
            }
            set {
                this.productListField = value;
                this.RaisePropertyChanged("productList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProviderObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string providerCodeField;
        
        private int providerIDField;
        
        private string providerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string providerCode {
            get {
                return this.providerCodeField;
            }
            set {
                this.providerCodeField = value;
                this.RaisePropertyChanged("providerCode");
            }
        }
        
        /// <remarks/>
        public int providerID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("providerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string providerName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
                this.RaisePropertyChanged("providerName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProviderListObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private ProviderObject[] providerListField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ProviderObject[] providerList {
            get {
                return this.providerListField;
            }
            set {
                this.providerListField = value;
                this.RaisePropertyChanged("providerList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CategoryObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int categoryIdField;
        
        private string categoryNameField;
        
        /// <remarks/>
        public int categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("categoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string categoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
                this.RaisePropertyChanged("categoryName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CategoryListObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CategoryObject[] categoryListField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CategoryObject[] categoryList {
            get {
                return this.categoryListField;
            }
            set {
                this.categoryListField = value;
                this.RaisePropertyChanged("categoryList");
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CheckTargetObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string providerCodeField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string providerCode {
            get {
                return this.providerCodeField;
            }
            set {
                this.providerCodeField = value;
                this.RaisePropertyChanged("providerCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class SignInResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string tokenField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class BalanceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long dataValueField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private int transIDField;
        
        /// <remarks/>
        public long dataValue {
            get {
                return this.dataValueField;
            }
            set {
                this.dataValueField = value;
                this.RaisePropertyChanged("dataValue");
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        public int transID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
                this.RaisePropertyChanged("transID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TopupInterfaceChannel : IZISoft.IMediaService.TopupInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TopupInterfaceClient : System.ServiceModel.ClientBase<IZISoft.IMediaService.TopupInterface>, IZISoft.IMediaService.TopupInterface {
        
        public TopupInterfaceClient() {
        }
        
        public TopupInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TopupInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopupInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TopupInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IZISoft.IMediaService.SignOutResult signOut(string username, string token) {
            return base.Channel.signOut(username, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.SignOutResult> signOutAsync(string username, string token) {
            return base.Channel.signOutAsync(username, token);
        }
        
        public string checkConnection() {
            return base.Channel.checkConnection();
        }
        
        public System.Threading.Tasks.Task<string> checkConnectionAsync() {
            return base.Channel.checkConnectionAsync();
        }
        
        public IZISoft.IMediaService.BalanceResult queryBalance(string username, string requestID, string token) {
            return base.Channel.queryBalance(username, requestID, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.BalanceResult> queryBalanceAsync(string username, string requestID, string token) {
            return base.Channel.queryBalanceAsync(username, requestID, token);
        }
        
        public IZISoft.IMediaService.SignInResult signInAsPartner(string username, string password) {
            return base.Channel.signInAsPartner(username, password);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.SignInResult> signInAsPartnerAsync(string username, string password) {
            return base.Channel.signInAsPartnerAsync(username, password);
        }
        
        public bool checkPhoneNumber(string phoneNumber) {
            return base.Channel.checkPhoneNumber(phoneNumber);
        }
        
        public System.Threading.Tasks.Task<bool> checkPhoneNumberAsync(string phoneNumber) {
            return base.Channel.checkPhoneNumberAsync(phoneNumber);
        }
        
        public IZISoft.IMediaService.CheckTargetObject checkTargetAccount(string username, string session, string targetAcount, string providerCode) {
            return base.Channel.checkTargetAccount(username, session, targetAcount, providerCode);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.CheckTargetObject> checkTargetAccountAsync(string username, string session, string targetAcount, string providerCode) {
            return base.Channel.checkTargetAccountAsync(username, session, targetAcount, providerCode);
        }
        
        public IZISoft.IMediaService.CategoryListObject partnerGetListCategories(string username, string token) {
            return base.Channel.partnerGetListCategories(username, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.CategoryListObject> partnerGetListCategoriesAsync(string username, string token) {
            return base.Channel.partnerGetListCategoriesAsync(username, token);
        }
        
        public IZISoft.IMediaService.ProviderListObject partnerGetListProviderOfCategory(string username, int categoryId, string token) {
            return base.Channel.partnerGetListProviderOfCategory(username, categoryId, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.ProviderListObject> partnerGetListProviderOfCategoryAsync(string username, int categoryId, string token) {
            return base.Channel.partnerGetListProviderOfCategoryAsync(username, categoryId, token);
        }
        
        public IZISoft.IMediaService.ProductListObject partnerGetListProductOfCategoryServiceProvider(string username, int categoryId, int providerId, string token) {
            return base.Channel.partnerGetListProductOfCategoryServiceProvider(username, categoryId, providerId, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.ProductListObject> partnerGetListProductOfCategoryServiceProviderAsync(string username, int categoryId, int providerId, string token) {
            return base.Channel.partnerGetListProductOfCategoryServiceProviderAsync(username, categoryId, providerId, token);
        }
        
        public IZISoft.IMediaService.LevelResult getListValueLevels(string username, string token) {
            return base.Channel.getListValueLevels(username, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.LevelResult> getListValueLevelsAsync(string username, string token) {
            return base.Channel.getListValueLevelsAsync(username, token);
        }
        
        public IZISoft.IMediaService.ProductInfo getProductInformation(string username, int productID, string token) {
            return base.Channel.getProductInformation(username, productID, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.ProductInfo> getProductInformationAsync(string username, int productID, string token) {
            return base.Channel.getProductInformationAsync(username, productID, token);
        }
        
        public IZISoft.IMediaService.CheckProducts[] partnerCheckProduct(string username, string token, int categoryId, int providerId) {
            return base.Channel.partnerCheckProduct(username, token, categoryId, providerId);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.CheckProducts[]> partnerCheckProductAsync(string username, string token, int categoryId, int providerId) {
            return base.Channel.partnerCheckProductAsync(username, token, categoryId, providerId);
        }
        
        public IZISoft.IMediaService.CheckProductsDetail[] partnerCheckProductDetail(string username, string token, IZISoft.IMediaService.CheckProductsDetail[] checkProducts) {
            return base.Channel.partnerCheckProductDetail(username, token, checkProducts);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.CheckProductsDetail[]> partnerCheckProductDetailAsync(string username, string token, IZISoft.IMediaService.CheckProductsDetail[] checkProducts) {
            return base.Channel.partnerCheckProductDetailAsync(username, token, checkProducts);
        }
        
        public IZISoft.IMediaService.ChangePasswordResult partnerChangePassword(string username, string oldPassword, string newPassword, string token) {
            return base.Channel.partnerChangePassword(username, oldPassword, newPassword, token);
        }
        
        public System.Threading.Tasks.Task<IZISoft.IMediaService.ChangePasswordResult> partnerChangePasswordAsync(string username, string oldPassword, string newPassword, string token) {
            return base.Channel.partnerChangePasswordAsync(username, oldPassword, newPassword, token);
        }
        
        public string requestHandle(string requestData) {
            return base.Channel.requestHandle(requestData);
        }
        
        public System.Threading.Tasks.Task<string> requestHandleAsync(string requestData) {
            return base.Channel.requestHandleAsync(requestData);
        }
    }
}
