//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace APIProxy.VTTService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TopupCallbackAppVTTSoap", Namespace="http://tempuri.org/")]
    public partial class TopupCallbackAppVTT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallbackOperationCompleted;
        
        /// <remarks/>
        public TopupCallbackAppVTT(string url) {
            //this.Url = "http://localhost:59599/TopupCallbackAppVTT.asmx";
            this.Url = url;
        }
        
        /// <remarks/>
        public event CallbackCompletedEventHandler CallbackCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Callback", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Callback(string transactionId, int status, int amount, string message, string logContent, string sign) {
            object[] results = this.Invoke("Callback", new object[] {
                        transactionId,
                        status,
                        amount,
                        message,
                        logContent,
                        sign});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCallback(string transactionId, int status, int amount, string message, string logContent, string sign, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Callback", new object[] {
                        transactionId,
                        status,
                        amount,
                        message,
                        logContent,
                        sign}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCallback(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CallbackAsync(string transactionId, int status, int amount, string message, string logContent, string sign) {
            this.CallbackAsync(transactionId, status, amount, message, logContent, sign, null);
        }
        
        /// <remarks/>
        public void CallbackAsync(string transactionId, int status, int amount, string message, string logContent, string sign, object userState) {
            if ((this.CallbackOperationCompleted == null)) {
                this.CallbackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallbackOperationCompleted);
            }
            this.InvokeAsync("Callback", new object[] {
                        transactionId,
                        status,
                        amount,
                        message,
                        logContent,
                        sign}, this.CallbackOperationCompleted, userState);
        }
        
        private void OnCallbackOperationCompleted(object arg) {
            if ((this.CallbackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallbackCompleted(this, new CallbackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void CallbackCompletedEventHandler(object sender, CallbackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
