//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


namespace VPGServiceProxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "VPGServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class VPGService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback RequestOperationCompleted;

        /// <remarks/>
        public VPGService(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event RequestCompletedEventHandler RequestCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Request", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Request(string partnerCode, string serviceCode, string commandCode, string requestContent, string signature)
        {
            object[] results = this.Invoke("Request", new object[] {
                    partnerCode,
                    serviceCode,
                    commandCode,
                    requestContent,
                    signature});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequest(string partnerCode, string serviceCode, string commandCode, string requestContent, string signature, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Request", new object[] {
                    partnerCode,
                    serviceCode,
                    commandCode,
                    requestContent,
                    signature}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestAsync(string partnerCode, string serviceCode, string commandCode, string requestContent, string signature)
        {
            this.RequestAsync(partnerCode, serviceCode, commandCode, requestContent, signature, null);
        }

        /// <remarks/>
        public void RequestAsync(string partnerCode, string serviceCode, string commandCode, string requestContent, string signature, object userState)
        {
            if ((this.RequestOperationCompleted == null))
            {
                this.RequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestOperationCompleted);
            }
            this.InvokeAsync("Request", new object[] {
                    partnerCode,
                    serviceCode,
                    commandCode,
                    requestContent,
                    signature}, this.RequestOperationCompleted, userState);
        }

        private void OnRequestOperationCompleted(object arg)
        {
            if ((this.RequestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestCompleted(this, new RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void RequestCompletedEventHandler(object sender, RequestCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}