//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 

namespace Libs.TopupPartner.VNPTEPAY
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "InterfacesSoapBinding", Namespace = "http://services.epay")]
    public partial class InterfacesService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback topupOperationCompleted;

        private System.Threading.SendOrPostCallback echoOperationCompleted;

        private System.Threading.SendOrPostCallback checkStoreOperationCompleted;

        private System.Threading.SendOrPostCallback paymentCDVOperationCompleted;

        private System.Threading.SendOrPostCallback downloadSoftpinOperationCompleted;

        private System.Threading.SendOrPostCallback checkTransOperationCompleted;

        private System.Threading.SendOrPostCallback queryBalanceOperationCompleted;

        private System.Threading.SendOrPostCallback checkOrdersCDVOperationCompleted;

        private System.Threading.SendOrPostCallback reDownloadSoftpinOperationCompleted;

        /// <remarks/>
        public InterfacesService(string url)
        {
            //this.Url = "http://itopup-test.megapay.net.vn:8086/CDV_Partner_Services_V1.0/services/Interfaces";
            this.Url = url;
        }

        /// <remarks/>
        public event topupCompletedEventHandler topupCompleted;

        /// <remarks/>
        public event echoCompletedEventHandler echoCompleted;

        /// <remarks/>
        public event checkStoreCompletedEventHandler checkStoreCompleted;

        /// <remarks/>
        public event paymentCDVCompletedEventHandler paymentCDVCompleted;

        /// <remarks/>
        public event downloadSoftpinCompletedEventHandler downloadSoftpinCompleted;

        /// <remarks/>
        public event checkTransCompletedEventHandler checkTransCompleted;

        /// <remarks/>
        public event queryBalanceCompletedEventHandler queryBalanceCompleted;

        /// <remarks/>
        public event checkOrdersCDVCompletedEventHandler checkOrdersCDVCompleted;

        /// <remarks/>
        public event reDownloadSoftpinCompletedEventHandler reDownloadSoftpinCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("topupReturn")]
        public TopupResult topup(string requestId, string partnerName, string provider, string target, int amount, string sign)
        {
            object[] results = this.Invoke("topup", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    target,
                    amount,
                    sign});
            return ((TopupResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Begintopup(string requestId, string partnerName, string provider, string target, int amount, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("topup", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    target,
                    amount,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public TopupResult Endtopup(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((TopupResult)(results[0]));
        }

        /// <remarks/>
        public void topupAsync(string requestId, string partnerName, string provider, string target, int amount, string sign)
        {
            this.topupAsync(requestId, partnerName, provider, target, amount, sign, null);
        }

        /// <remarks/>
        public void topupAsync(string requestId, string partnerName, string provider, string target, int amount, string sign, object userState)
        {
            if ((this.topupOperationCompleted == null))
            {
                this.topupOperationCompleted = new System.Threading.SendOrPostCallback(this.OntopupOperationCompleted);
            }
            this.InvokeAsync("topup", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    target,
                    amount,
                    sign}, this.topupOperationCompleted, userState);
        }

        private void OntopupOperationCompleted(object arg)
        {
            if ((this.topupCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.topupCompleted(this, new topupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("echoReturn")]
        public int echo()
        {
            object[] results = this.Invoke("echo", new object[0]);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginecho(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("echo", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public int Endecho(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void echoAsync()
        {
            this.echoAsync(null);
        }

        /// <remarks/>
        public void echoAsync(object userState)
        {
            if ((this.echoOperationCompleted == null))
            {
                this.echoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoOperationCompleted);
            }
            this.InvokeAsync("echo", new object[0], this.echoOperationCompleted, userState);
        }

        private void OnechoOperationCompleted(object arg)
        {
            if ((this.echoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoCompleted(this, new echoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("checkStoreReturn")]
        public int checkStore(string partnerName, string provider, int amount, string sign)
        {
            object[] results = this.Invoke("checkStore", new object[] {
                    partnerName,
                    provider,
                    amount,
                    sign});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegincheckStore(string partnerName, string provider, int amount, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("checkStore", new object[] {
                    partnerName,
                    provider,
                    amount,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public int EndcheckStore(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void checkStoreAsync(string partnerName, string provider, int amount, string sign)
        {
            this.checkStoreAsync(partnerName, provider, amount, sign, null);
        }

        /// <remarks/>
        public void checkStoreAsync(string partnerName, string provider, int amount, string sign, object userState)
        {
            if ((this.checkStoreOperationCompleted == null))
            {
                this.checkStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckStoreOperationCompleted);
            }
            this.InvokeAsync("checkStore", new object[] {
                    partnerName,
                    provider,
                    amount,
                    sign}, this.checkStoreOperationCompleted, userState);
        }

        private void OncheckStoreOperationCompleted(object arg)
        {
            if ((this.checkStoreCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkStoreCompleted(this, new checkStoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("paymentCDVReturn")]
        public PaymentCdvResult paymentCDV(string requestId, string partnerName, string provider, int type, string account, long amount, int timeOut, string sign)
        {
            object[] results = this.Invoke("paymentCDV", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    type,
                    account,
                    amount,
                    timeOut,
                    sign});
            return ((PaymentCdvResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginpaymentCDV(string requestId, string partnerName, string provider, int type, string account, long amount, int timeOut, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("paymentCDV", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    type,
                    account,
                    amount,
                    timeOut,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public PaymentCdvResult EndpaymentCDV(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((PaymentCdvResult)(results[0]));
        }

        /// <remarks/>
        public void paymentCDVAsync(string requestId, string partnerName, string provider, int type, string account, long amount, int timeOut, string sign)
        {
            this.paymentCDVAsync(requestId, partnerName, provider, type, account, amount, timeOut, sign, null);
        }

        /// <remarks/>
        public void paymentCDVAsync(string requestId, string partnerName, string provider, int type, string account, long amount, int timeOut, string sign, object userState)
        {
            if ((this.paymentCDVOperationCompleted == null))
            {
                this.paymentCDVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpaymentCDVOperationCompleted);
            }
            this.InvokeAsync("paymentCDV", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    type,
                    account,
                    amount,
                    timeOut,
                    sign}, this.paymentCDVOperationCompleted, userState);
        }

        private void OnpaymentCDVOperationCompleted(object arg)
        {
            if ((this.paymentCDVCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.paymentCDVCompleted(this, new paymentCDVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("downloadSoftpinReturn")]
        public DownloadSoftpinResult downloadSoftpin(string requestId, string partnerName, string provider, int amount, int quantity, string sign)
        {
            object[] results = this.Invoke("downloadSoftpin", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    amount,
                    quantity,
                    sign});
            return ((DownloadSoftpinResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegindownloadSoftpin(string requestId, string partnerName, string provider, int amount, int quantity, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("downloadSoftpin", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    amount,
                    quantity,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public DownloadSoftpinResult EnddownloadSoftpin(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DownloadSoftpinResult)(results[0]));
        }

        /// <remarks/>
        public void downloadSoftpinAsync(string requestId, string partnerName, string provider, int amount, int quantity, string sign)
        {
            this.downloadSoftpinAsync(requestId, partnerName, provider, amount, quantity, sign, null);
        }

        /// <remarks/>
        public void downloadSoftpinAsync(string requestId, string partnerName, string provider, int amount, int quantity, string sign, object userState)
        {
            if ((this.downloadSoftpinOperationCompleted == null))
            {
                this.downloadSoftpinOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadSoftpinOperationCompleted);
            }
            this.InvokeAsync("downloadSoftpin", new object[] {
                    requestId,
                    partnerName,
                    provider,
                    amount,
                    quantity,
                    sign}, this.downloadSoftpinOperationCompleted, userState);
        }

        private void OndownloadSoftpinOperationCompleted(object arg)
        {
            if ((this.downloadSoftpinCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadSoftpinCompleted(this, new downloadSoftpinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("checkTransReturn")]
        public CheckTransResult checkTrans(string requestId, string partnerName, int type, string sign)
        {
            object[] results = this.Invoke("checkTrans", new object[] {
                    requestId,
                    partnerName,
                    type,
                    sign});
            return ((CheckTransResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegincheckTrans(string requestId, string partnerName, int type, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("checkTrans", new object[] {
                    requestId,
                    partnerName,
                    type,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public CheckTransResult EndcheckTrans(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CheckTransResult)(results[0]));
        }

        /// <remarks/>
        public void checkTransAsync(string requestId, string partnerName, int type, string sign)
        {
            this.checkTransAsync(requestId, partnerName, type, sign, null);
        }

        /// <remarks/>
        public void checkTransAsync(string requestId, string partnerName, int type, string sign, object userState)
        {
            if ((this.checkTransOperationCompleted == null))
            {
                this.checkTransOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckTransOperationCompleted);
            }
            this.InvokeAsync("checkTrans", new object[] {
                    requestId,
                    partnerName,
                    type,
                    sign}, this.checkTransOperationCompleted, userState);
        }

        private void OncheckTransOperationCompleted(object arg)
        {
            if ((this.checkTransCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkTransCompleted(this, new checkTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("queryBalanceReturn")]
        public QueryBalanceResult queryBalance(string partnerName, string sign)
        {
            object[] results = this.Invoke("queryBalance", new object[] {
                    partnerName,
                    sign});
            return ((QueryBalanceResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginqueryBalance(string partnerName, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryBalance", new object[] {
                    partnerName,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public QueryBalanceResult EndqueryBalance(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((QueryBalanceResult)(results[0]));
        }

        /// <remarks/>
        public void queryBalanceAsync(string partnerName, string sign)
        {
            this.queryBalanceAsync(partnerName, sign, null);
        }

        /// <remarks/>
        public void queryBalanceAsync(string partnerName, string sign, object userState)
        {
            if ((this.queryBalanceOperationCompleted == null))
            {
                this.queryBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBalanceOperationCompleted);
            }
            this.InvokeAsync("queryBalance", new object[] {
                    partnerName,
                    sign}, this.queryBalanceOperationCompleted, userState);
        }

        private void OnqueryBalanceOperationCompleted(object arg)
        {
            if ((this.queryBalanceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryBalanceCompleted(this, new queryBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("checkOrdersCDVReturn")]
        public CheckOrdesrCDVResult checkOrdersCDV(string requestId, string partnerName, string sign)
        {
            object[] results = this.Invoke("checkOrdersCDV", new object[] {
                    requestId,
                    partnerName,
                    sign});
            return ((CheckOrdesrCDVResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegincheckOrdersCDV(string requestId, string partnerName, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("checkOrdersCDV", new object[] {
                    requestId,
                    partnerName,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public CheckOrdesrCDVResult EndcheckOrdersCDV(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CheckOrdesrCDVResult)(results[0]));
        }

        /// <remarks/>
        public void checkOrdersCDVAsync(string requestId, string partnerName, string sign)
        {
            this.checkOrdersCDVAsync(requestId, partnerName, sign, null);
        }

        /// <remarks/>
        public void checkOrdersCDVAsync(string requestId, string partnerName, string sign, object userState)
        {
            if ((this.checkOrdersCDVOperationCompleted == null))
            {
                this.checkOrdersCDVOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckOrdersCDVOperationCompleted);
            }
            this.InvokeAsync("checkOrdersCDV", new object[] {
                    requestId,
                    partnerName,
                    sign}, this.checkOrdersCDVOperationCompleted, userState);
        }

        private void OncheckOrdersCDVOperationCompleted(object arg)
        {
            if ((this.checkOrdersCDVCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkOrdersCDVCompleted(this, new checkOrdersCDVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://services.epay", ResponseNamespace = "http://services.epay")]
        [return: System.Xml.Serialization.SoapElementAttribute("reDownloadSoftpinReturn")]
        public DownloadSoftpinResult reDownloadSoftpin(string requestId, string partnerName, string sign)
        {
            object[] results = this.Invoke("reDownloadSoftpin", new object[] {
                    requestId,
                    partnerName,
                    sign});
            return ((DownloadSoftpinResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginreDownloadSoftpin(string requestId, string partnerName, string sign, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("reDownloadSoftpin", new object[] {
                    requestId,
                    partnerName,
                    sign}, callback, asyncState);
        }

        /// <remarks/>
        public DownloadSoftpinResult EndreDownloadSoftpin(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DownloadSoftpinResult)(results[0]));
        }

        /// <remarks/>
        public void reDownloadSoftpinAsync(string requestId, string partnerName, string sign)
        {
            this.reDownloadSoftpinAsync(requestId, partnerName, sign, null);
        }

        /// <remarks/>
        public void reDownloadSoftpinAsync(string requestId, string partnerName, string sign, object userState)
        {
            if ((this.reDownloadSoftpinOperationCompleted == null))
            {
                this.reDownloadSoftpinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreDownloadSoftpinOperationCompleted);
            }
            this.InvokeAsync("reDownloadSoftpin", new object[] {
                    requestId,
                    partnerName,
                    sign}, this.reDownloadSoftpinOperationCompleted, userState);
        }

        private void OnreDownloadSoftpinOperationCompleted(object arg)
        {
            if ((this.reDownloadSoftpinCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reDownloadSoftpinCompleted(this, new reDownloadSoftpinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://services.epay")]
    public partial class TopupResult
    {

        private int errorCodeField;

        private string messageField;

        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://services.epay")]
    public partial class CheckOrdesrCDVResult
    {

        private long amountTopupSuccessField;

        private int errorCodeField;

        private string messageField;

        /// <remarks/>
        public long amountTopupSuccess
        {
            get
            {
                return this.amountTopupSuccessField;
            }
            set
            {
                this.amountTopupSuccessField = value;
            }
        }

        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://services.epay")]
    public partial class QueryBalanceResult
    {

        private long balance_avaiableField;

        private long balance_bonusField;

        private long balance_debitField;

        private long balance_moneyField;

        private int errorCodeField;

        private string messageField;

        private string partnerNameField;

        /// <remarks/>
        public long balance_avaiable
        {
            get
            {
                return this.balance_avaiableField;
            }
            set
            {
                this.balance_avaiableField = value;
            }
        }

        /// <remarks/>
        public long balance_bonus
        {
            get
            {
                return this.balance_bonusField;
            }
            set
            {
                this.balance_bonusField = value;
            }
        }

        /// <remarks/>
        public long balance_debit
        {
            get
            {
                return this.balance_debitField;
            }
            set
            {
                this.balance_debitField = value;
            }
        }

        /// <remarks/>
        public long balance_money
        {
            get
            {
                return this.balance_moneyField;
            }
            set
            {
                this.balance_moneyField = value;
            }
        }

        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string partnerName
        {
            get
            {
                return this.partnerNameField;
            }
            set
            {
                this.partnerNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://services.epay")]
    public partial class CheckTransResult
    {

        private int errorCodeField;

        private string messageField;

        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://services.epay")]
    public partial class DownloadSoftpinResult
    {

        private int errorCodeField;

        private string listCardsField;

        private string messageField;

        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string listCards
        {
            get
            {
                return this.listCardsField;
            }
            set
            {
                this.listCardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://services.epay")]
    public partial class PaymentCdvResult
    {

        private long amountPendingField;

        private long amountRequestField;

        private long amountTopupSuccessField;

        private int errorCodeField;

        private string messageField;

        private string providerField;

        private string targetField;

        private int typeField;

        /// <remarks/>
        public long amountPending
        {
            get
            {
                return this.amountPendingField;
            }
            set
            {
                this.amountPendingField = value;
            }
        }

        /// <remarks/>
        public long amountRequest
        {
            get
            {
                return this.amountRequestField;
            }
            set
            {
                this.amountRequestField = value;
            }
        }

        /// <remarks/>
        public long amountTopupSuccess
        {
            get
            {
                return this.amountTopupSuccessField;
            }
            set
            {
                this.amountTopupSuccessField = value;
            }
        }

        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string provider
        {
            get
            {
                return this.providerField;
            }
            set
            {
                this.providerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        /// <remarks/>
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void topupCompletedEventHandler(object sender, topupCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class topupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal topupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public TopupResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TopupResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void echoCompletedEventHandler(object sender, echoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal echoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void checkStoreCompletedEventHandler(object sender, checkStoreCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkStoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal checkStoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void paymentCDVCompletedEventHandler(object sender, paymentCDVCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class paymentCDVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal paymentCDVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PaymentCdvResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PaymentCdvResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void downloadSoftpinCompletedEventHandler(object sender, downloadSoftpinCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadSoftpinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal downloadSoftpinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DownloadSoftpinResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DownloadSoftpinResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void checkTransCompletedEventHandler(object sender, checkTransCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkTransCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal checkTransCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CheckTransResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CheckTransResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void queryBalanceCompletedEventHandler(object sender, queryBalanceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal queryBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public QueryBalanceResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((QueryBalanceResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void checkOrdersCDVCompletedEventHandler(object sender, checkOrdersCDVCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkOrdersCDVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal checkOrdersCDVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CheckOrdesrCDVResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CheckOrdesrCDVResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void reDownloadSoftpinCompletedEventHandler(object sender, reDownloadSoftpinCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reDownloadSoftpinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal reDownloadSoftpinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DownloadSoftpinResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DownloadSoftpinResult)(this.results[0]));
            }
        }
    }
}