//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace Libs.CardTelco.VinaHub
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "TopupAppVTTServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class TopupMobile : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback RequestTopupOperationCompleted;

        /// <remarks/>
        public TopupMobile(string url)
        {
            //this.Url = "http://localhost:59599/TopupAppVTT.asmx";
            this.Url = url;
        }

        /// <remarks/>
        public event RequestTopupCompletedEventHandler RequestTopupCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestTopup", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestTopup(string transactionId, string telco, string partnerCode, string providerCode, string cardSerial, string cardCode, string simTarget, int amount)
        {
            object[] results = this.Invoke("RequestTopup", new object[] {
                        transactionId,
                        telco,
                        partnerCode,
                        providerCode,
                        cardSerial,
                        cardCode,
                        simTarget,
                        amount});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestTopup(string transactionId, string telco, string partnerCode, string providerCode, string cardSerial, string cardCode, string simTarget, int amount, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestTopup", new object[] {
                        transactionId,
                        telco,
                        partnerCode,
                        providerCode,
                        cardSerial,
                        cardCode,
                        simTarget,
                        amount}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestTopup(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestTopupAsync(string transactionId, string telco, string partnerCode, string providerCode, string cardSerial, string cardCode, string simTarget, int amount)
        {
            this.RequestTopupAsync(transactionId, telco, partnerCode, providerCode, cardSerial, cardCode, simTarget, amount, null);
        }

        /// <remarks/>
        public void RequestTopupAsync(string transactionId, string telco, string partnerCode, string providerCode, string cardSerial, string cardCode, string simTarget, int amount, object userState)
        {
            if ((this.RequestTopupOperationCompleted == null))
            {
                this.RequestTopupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestTopupOperationCompleted);
            }
            this.InvokeAsync("RequestTopup", new object[] {
                        transactionId,
                        telco,
                        partnerCode,
                        providerCode,
                        cardSerial,
                        cardCode,
                        simTarget,
                        amount}, this.RequestTopupOperationCompleted, userState);
        }

        private void OnRequestTopupOperationCompleted(object arg)
        {
            if ((this.RequestTopupCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestTopupCompleted(this, new RequestTopupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void RequestTopupCompletedEventHandler(object sender, RequestTopupCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestTopupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestTopupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
