//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGate.GateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://exchange.partner.service.itel.vn", ConfigurationName="GateService.CardToCash")]
    public interface CardToCash {
        
        // CODEGEN: Generating message contract since element name input from namespace http://exchange.partner.service.itel.vn is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        APIGate.GateService.checkTransactionResponse checkTransaction(APIGate.GateService.checkTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<APIGate.GateService.checkTransactionResponse> checkTransactionAsync(APIGate.GateService.checkTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://exchange.partner.service.itel.vn is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        APIGate.GateService.exchangeCardResponse exchangeCard(APIGate.GateService.exchangeCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<APIGate.GateService.exchangeCardResponse> exchangeCardAsync(APIGate.GateService.exchangeCardRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://exchange.partner.service.itel.vn is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        APIGate.GateService.exchangeCardWithValueResponse exchangeCardWithValue(APIGate.GateService.exchangeCardWithValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<APIGate.GateService.exchangeCardWithValueResponse> exchangeCardWithValueAsync(APIGate.GateService.exchangeCardWithValueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkTransaction", Namespace="http://exchange.partner.service.itel.vn", Order=0)]
        public APIGate.GateService.checkTransactionRequestBody Body;
        
        public checkTransactionRequest() {
        }
        
        public checkTransactionRequest(APIGate.GateService.checkTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exchange.partner.service.itel.vn")]
    public partial class checkTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public checkTransactionRequestBody() {
        }
        
        public checkTransactionRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkTransactionResponse", Namespace="http://exchange.partner.service.itel.vn", Order=0)]
        public APIGate.GateService.checkTransactionResponseBody Body;
        
        public checkTransactionResponse() {
        }
        
        public checkTransactionResponse(APIGate.GateService.checkTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exchange.partner.service.itel.vn")]
    public partial class checkTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkTransactionReturn;
        
        public checkTransactionResponseBody() {
        }
        
        public checkTransactionResponseBody(string checkTransactionReturn) {
            this.checkTransactionReturn = checkTransactionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeCard", Namespace="http://exchange.partner.service.itel.vn", Order=0)]
        public APIGate.GateService.exchangeCardRequestBody Body;
        
        public exchangeCardRequest() {
        }
        
        public exchangeCardRequest(APIGate.GateService.exchangeCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exchange.partner.service.itel.vn")]
    public partial class exchangeCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public exchangeCardRequestBody() {
        }
        
        public exchangeCardRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeCardResponse", Namespace="http://exchange.partner.service.itel.vn", Order=0)]
        public APIGate.GateService.exchangeCardResponseBody Body;
        
        public exchangeCardResponse() {
        }
        
        public exchangeCardResponse(APIGate.GateService.exchangeCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exchange.partner.service.itel.vn")]
    public partial class exchangeCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string exchangeCardReturn;
        
        public exchangeCardResponseBody() {
        }
        
        public exchangeCardResponseBody(string exchangeCardReturn) {
            this.exchangeCardReturn = exchangeCardReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeCardWithValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeCardWithValue", Namespace="http://exchange.partner.service.itel.vn", Order=0)]
        public APIGate.GateService.exchangeCardWithValueRequestBody Body;
        
        public exchangeCardWithValueRequest() {
        }
        
        public exchangeCardWithValueRequest(APIGate.GateService.exchangeCardWithValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exchange.partner.service.itel.vn")]
    public partial class exchangeCardWithValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long cardValue;
        
        public exchangeCardWithValueRequestBody() {
        }
        
        public exchangeCardWithValueRequestBody(string input, long cardValue) {
            this.input = input;
            this.cardValue = cardValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exchangeCardWithValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exchangeCardWithValueResponse", Namespace="http://exchange.partner.service.itel.vn", Order=0)]
        public APIGate.GateService.exchangeCardWithValueResponseBody Body;
        
        public exchangeCardWithValueResponse() {
        }
        
        public exchangeCardWithValueResponse(APIGate.GateService.exchangeCardWithValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://exchange.partner.service.itel.vn")]
    public partial class exchangeCardWithValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string exchangeCardWithValueReturn;
        
        public exchangeCardWithValueResponseBody() {
        }
        
        public exchangeCardWithValueResponseBody(string exchangeCardWithValueReturn) {
            this.exchangeCardWithValueReturn = exchangeCardWithValueReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardToCashChannel : APIGate.GateService.CardToCash, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardToCashClient : System.ServiceModel.ClientBase<APIGate.GateService.CardToCash>, APIGate.GateService.CardToCash {
        
        public CardToCashClient() {
        }
        
        public CardToCashClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardToCashClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardToCashClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardToCashClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIGate.GateService.checkTransactionResponse APIGate.GateService.CardToCash.checkTransaction(APIGate.GateService.checkTransactionRequest request) {
            return base.Channel.checkTransaction(request);
        }
        
        public string checkTransaction(string input) {
            APIGate.GateService.checkTransactionRequest inValue = new APIGate.GateService.checkTransactionRequest();
            inValue.Body = new APIGate.GateService.checkTransactionRequestBody();
            inValue.Body.input = input;
            APIGate.GateService.checkTransactionResponse retVal = ((APIGate.GateService.CardToCash)(this)).checkTransaction(inValue);
            return retVal.Body.checkTransactionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIGate.GateService.checkTransactionResponse> APIGate.GateService.CardToCash.checkTransactionAsync(APIGate.GateService.checkTransactionRequest request) {
            return base.Channel.checkTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIGate.GateService.checkTransactionResponse> checkTransactionAsync(string input) {
            APIGate.GateService.checkTransactionRequest inValue = new APIGate.GateService.checkTransactionRequest();
            inValue.Body = new APIGate.GateService.checkTransactionRequestBody();
            inValue.Body.input = input;
            return ((APIGate.GateService.CardToCash)(this)).checkTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIGate.GateService.exchangeCardResponse APIGate.GateService.CardToCash.exchangeCard(APIGate.GateService.exchangeCardRequest request) {
            return base.Channel.exchangeCard(request);
        }
        
        public string exchangeCard(string input) {
            APIGate.GateService.exchangeCardRequest inValue = new APIGate.GateService.exchangeCardRequest();
            inValue.Body = new APIGate.GateService.exchangeCardRequestBody();
            inValue.Body.input = input;
            APIGate.GateService.exchangeCardResponse retVal = ((APIGate.GateService.CardToCash)(this)).exchangeCard(inValue);
            return retVal.Body.exchangeCardReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIGate.GateService.exchangeCardResponse> APIGate.GateService.CardToCash.exchangeCardAsync(APIGate.GateService.exchangeCardRequest request) {
            return base.Channel.exchangeCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIGate.GateService.exchangeCardResponse> exchangeCardAsync(string input) {
            APIGate.GateService.exchangeCardRequest inValue = new APIGate.GateService.exchangeCardRequest();
            inValue.Body = new APIGate.GateService.exchangeCardRequestBody();
            inValue.Body.input = input;
            return ((APIGate.GateService.CardToCash)(this)).exchangeCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIGate.GateService.exchangeCardWithValueResponse APIGate.GateService.CardToCash.exchangeCardWithValue(APIGate.GateService.exchangeCardWithValueRequest request) {
            return base.Channel.exchangeCardWithValue(request);
        }
        
        public string exchangeCardWithValue(string input, long cardValue) {
            APIGate.GateService.exchangeCardWithValueRequest inValue = new APIGate.GateService.exchangeCardWithValueRequest();
            inValue.Body = new APIGate.GateService.exchangeCardWithValueRequestBody();
            inValue.Body.input = input;
            inValue.Body.cardValue = cardValue;
            APIGate.GateService.exchangeCardWithValueResponse retVal = ((APIGate.GateService.CardToCash)(this)).exchangeCardWithValue(inValue);
            return retVal.Body.exchangeCardWithValueReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIGate.GateService.exchangeCardWithValueResponse> APIGate.GateService.CardToCash.exchangeCardWithValueAsync(APIGate.GateService.exchangeCardWithValueRequest request) {
            return base.Channel.exchangeCardWithValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIGate.GateService.exchangeCardWithValueResponse> exchangeCardWithValueAsync(string input, long cardValue) {
            APIGate.GateService.exchangeCardWithValueRequest inValue = new APIGate.GateService.exchangeCardWithValueRequest();
            inValue.Body = new APIGate.GateService.exchangeCardWithValueRequestBody();
            inValue.Body.input = input;
            inValue.Body.cardValue = cardValue;
            return ((APIGate.GateService.CardToCash)(this)).exchangeCardWithValueAsync(inValue);
        }
    }
}
