//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
//File .wsdl cần thêm file .xsd để generate proxy

namespace Libs.CardTelco
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ScratchCardAPIPortBinding", Namespace = "http://api.scratchcard.viettel.com/")]
    public partial class ScratchCardAPIService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback topupCardOperationCompleted;

        private System.Threading.SendOrPostCallback queryCardStatusOperationCompleted;

        private System.Threading.SendOrPostCallback queryResultTransactionOperationCompleted;

        /// <remarks/>
        public ScratchCardAPIService(string URL)
        {
            this.Url = URL;
            //this.Url = "https://115.84.178.2:8444/ScratchCardAPI/ScratchCardAPI";
        }

        /// <remarks/>
        public event topupCardCompletedEventHandler topupCardCompleted;

        /// <remarks/>
        public event queryCardStatusCompletedEventHandler queryCardStatusCompleted;

        /// <remarks/>
        public event queryResultTransactionCompletedEventHandler queryResultTransactionCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://api.scratchcard.viettel.com/", ResponseNamespace = "http://api.scratchcard.viettel.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pnResponse topupCard([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string parnerID, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string passphase, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string cardSerial, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string pinCard, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string transId, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string provider, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string serviceName)
        {
            object[] results = this.Invoke("topupCard", new object[] {
                    parnerID,
                    passphase,
                    cardSerial,
                    pinCard,
                    transId,
                    provider,
                    serviceName});
            return ((pnResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegintopupCard(string parnerID, string passphase, string cardSerial, string pinCard, string transId, string provider, string serviceName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("topupCard", new object[] {
                    parnerID,
                    passphase,
                    cardSerial,
                    pinCard,
                    transId,
                    provider,
                    serviceName}, callback, asyncState);
        }

        /// <remarks/>
        public pnResponse EndtopupCard(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((pnResponse)(results[0]));
        }

        /// <remarks/>
        public void topupCardAsync(string parnerID, string passphase, string cardSerial, string pinCard, string transId, string provider, string serviceName)
        {
            this.topupCardAsync(parnerID, passphase, cardSerial, pinCard, transId, provider, serviceName, null);
        }

        /// <remarks/>
        public void topupCardAsync(string parnerID, string passphase, string cardSerial, string pinCard, string transId, string provider, string serviceName, object userState)
        {
            if ((this.topupCardOperationCompleted == null))
            {
                this.topupCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OntopupCardOperationCompleted);
            }
            this.InvokeAsync("topupCard", new object[] {
                    parnerID,
                    passphase,
                    cardSerial,
                    pinCard,
                    transId,
                    provider,
                    serviceName}, this.topupCardOperationCompleted, userState);
        }

        private void OntopupCardOperationCompleted(object arg)
        {
            if ((this.topupCardCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.topupCardCompleted(this, new topupCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://api.scratchcard.viettel.com/", ResponseNamespace = "http://api.scratchcard.viettel.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pnResponse queryCardStatus([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string sequence, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string partnerID, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string passphase, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string transId)
        {
            object[] results = this.Invoke("queryCardStatus", new object[] {
                    sequence,
                    partnerID,
                    passphase,
                    transId});
            return ((pnResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginqueryCardStatus(string sequence, string partnerID, string passphase, string transId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryCardStatus", new object[] {
                    sequence,
                    partnerID,
                    passphase,
                    transId}, callback, asyncState);
        }

        /// <remarks/>
        public pnResponse EndqueryCardStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((pnResponse)(results[0]));
        }

        /// <remarks/>
        public void queryCardStatusAsync(string sequence, string partnerID, string passphase, string transId)
        {
            this.queryCardStatusAsync(sequence, partnerID, passphase, transId, null);
        }

        /// <remarks/>
        public void queryCardStatusAsync(string sequence, string partnerID, string passphase, string transId, object userState)
        {
            if ((this.queryCardStatusOperationCompleted == null))
            {
                this.queryCardStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryCardStatusOperationCompleted);
            }
            this.InvokeAsync("queryCardStatus", new object[] {
                    sequence,
                    partnerID,
                    passphase,
                    transId}, this.queryCardStatusOperationCompleted, userState);
        }

        private void OnqueryCardStatusOperationCompleted(object arg)
        {
            if ((this.queryCardStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCardStatusCompleted(this, new queryCardStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://api.scratchcard.viettel.com/", ResponseNamespace = "http://api.scratchcard.viettel.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pnResponse queryResultTransaction([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string parnerID, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string passphase, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string originTransId, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string transId)
        {
            object[] results = this.Invoke("queryResultTransaction", new object[] {
                    parnerID,
                    passphase,
                    originTransId,
                    transId});
            return ((pnResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginqueryResultTransaction(string parnerID, string passphase, string originTransId, string transId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryResultTransaction", new object[] {
                    parnerID,
                    passphase,
                    originTransId,
                    transId}, callback, asyncState);
        }

        /// <remarks/>
        public pnResponse EndqueryResultTransaction(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((pnResponse)(results[0]));
        }

        /// <remarks/>
        public void queryResultTransactionAsync(string parnerID, string passphase, string originTransId, string transId)
        {
            this.queryResultTransactionAsync(parnerID, passphase, originTransId, transId, null);
        }

        /// <remarks/>
        public void queryResultTransactionAsync(string parnerID, string passphase, string originTransId, string transId, object userState)
        {
            if ((this.queryResultTransactionOperationCompleted == null))
            {
                this.queryResultTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryResultTransactionOperationCompleted);
            }
            this.InvokeAsync("queryResultTransaction", new object[] {
                    parnerID,
                    passphase,
                    originTransId,
                    transId}, this.queryResultTransactionOperationCompleted, userState);
        }

        private void OnqueryResultTransactionOperationCompleted(object arg)
        {
            if ((this.queryResultTransactionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryResultTransactionCompleted(this, new queryResultTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://api.scratchcard.viettel.com/")]
    public partial class pnResponse
    {

        private string amountField;

        private string cardSerialField;

        private string errorCodeField;

        private string errorMessageField;

        private string originTransIdField;

        private System.DateTime responseTimeField;

        private bool responseTimeFieldSpecified;

        private string transIdField;

        private pnResponse transInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardSerial
        {
            get
            {
                return this.cardSerialField;
            }
            set
            {
                this.cardSerialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string originTransId
        {
            get
            {
                return this.originTransIdField;
            }
            set
            {
                this.originTransIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime responseTime
        {
            get
            {
                return this.responseTimeField;
            }
            set
            {
                this.responseTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseTimeSpecified
        {
            get
            {
                return this.responseTimeFieldSpecified;
            }
            set
            {
                this.responseTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transId
        {
            get
            {
                return this.transIdField;
            }
            set
            {
                this.transIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pnResponse transInfo
        {
            get
            {
                return this.transInfoField;
            }
            set
            {
                this.transInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void topupCardCompletedEventHandler(object sender, topupCardCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class topupCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal topupCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public pnResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((pnResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void queryCardStatusCompletedEventHandler(object sender, queryCardStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCardStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal queryCardStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public pnResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((pnResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void queryResultTransactionCompletedEventHandler(object sender, queryResultTransactionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryResultTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal queryResultTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public pnResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((pnResponse)(this.results[0]));
            }
        }
    }
}