

namespace Libs.CardTelco._1Pay.KHD
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://vietpay.vn", ConfigurationName = "IVinaCardService")]
    public interface IVinaCardService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://vietpay.vn/IVinaCardService/VerifyCard", ReplyAction = "http://vietpay.vn/IVinaCardService/VerifyCardResponse")]
        string VerifyCard(string telco, string serial, string cardCode, string tranref, string partnerCode, string password, string signature, string importCode);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://vietpay.vn/IVinaCardService/VerifyCard", ReplyAction = "http://vietpay.vn/IVinaCardService/VerifyCardResponse")]
        System.IAsyncResult BeginVerifyCard(string telco, string serial, string cardCode, string tranref, string partnerCode, string password, string signature, string importCode, System.AsyncCallback callback, object asyncState);

        string EndVerifyCard(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "http://vietpay.vn/IVinaCardService/GetTransactionDetail", ReplyAction = "http://vietpay.vn/IVinaCardService/GetTransactionDetailResponse")]
        string GetTransactionDetail(string tranref, string partnerCode, string password, string signature);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://vietpay.vn/IVinaCardService/GetTransactionDetail", ReplyAction = "http://vietpay.vn/IVinaCardService/GetTransactionDetailResponse")]
        System.IAsyncResult BeginGetTransactionDetail(string tranref, string partnerCode, string password, string signature, System.AsyncCallback callback, object asyncState);

        string EndGetTransactionDetail(System.IAsyncResult result);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVinaCardServiceChannel : IVinaCardService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VinaCardServiceClient : System.ServiceModel.ClientBase<IVinaCardService>, IVinaCardService
    {

        public VinaCardServiceClient()
        {
        }

        public VinaCardServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public VinaCardServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public VinaCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public VinaCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string VerifyCard(string telco, string serial, string cardCode, string tranref, string partnerCode, string password, string signature, string importCode)
        {
            return base.Channel.VerifyCard(telco, serial, cardCode, tranref, partnerCode, password, signature, importCode);
        }

        public System.IAsyncResult BeginVerifyCard(string telco, string serial, string cardCode, string tranref, string partnerCode, string password, string signature, string importCode, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginVerifyCard(telco, serial, cardCode, tranref, partnerCode, password, signature, importCode, callback, asyncState);
        }

        public string EndVerifyCard(System.IAsyncResult result)
        {
            return base.Channel.EndVerifyCard(result);
        }

        public string GetTransactionDetail(string tranref, string partnerCode, string password, string signature)
        {
            return base.Channel.GetTransactionDetail(tranref, partnerCode, password, signature);
        }

        public System.IAsyncResult BeginGetTransactionDetail(string tranref, string partnerCode, string password, string signature, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetTransactionDetail(tranref, partnerCode, password, signature, callback, asyncState);
        }

        public string EndGetTransactionDetail(System.IAsyncResult result)
        {
            return base.Channel.EndGetTransactionDetail(result);
        }
    }

}
