//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace APITopupMobile.Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceBanTienSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceBanTien : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckStatusOperationCompleted;
        
        /// <remarks/>
        public ServiceBanTien(string url) {
            //this.Url = "http://27.72.63.148/Views/AutoBanTien/ServiceBanTien.asmx";
            this.Url = url;
        }
        
        /// <remarks/>
        public event AddQueueCompletedEventHandler AddQueueCompleted;
        
        /// <remarks/>
        public event CheckStatusCompletedEventHandler CheckStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddQueue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddQueue(string systemId, int type, string serial, string code, int price, string account, string keycode) {
            object[] results = this.Invoke("AddQueue", new object[] {
                        systemId,
                        type,
                        serial,
                        code,
                        price,
                        account,
                        keycode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddQueue(string systemId, int type, string serial, string code, int price, string account, string keycode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddQueue", new object[] {
                        systemId,
                        type,
                        serial,
                        code,
                        price,
                        account,
                        keycode}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndAddQueue(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddQueueAsync(string systemId, int type, string serial, string code, int price, string account, string keycode) {
            this.AddQueueAsync(systemId, type, serial, code, price, account, keycode, null);
        }
        
        /// <remarks/>
        public void AddQueueAsync(string systemId, int type, string serial, string code, int price, string account, string keycode, object userState) {
            if ((this.AddQueueOperationCompleted == null)) {
                this.AddQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddQueueOperationCompleted);
            }
            this.InvokeAsync("AddQueue", new object[] {
                        systemId,
                        type,
                        serial,
                        code,
                        price,
                        account,
                        keycode}, this.AddQueueOperationCompleted, userState);
        }
        
        private void OnAddQueueOperationCompleted(object arg) {
            if ((this.AddQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddQueueCompleted(this, new AddQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckStatus(int systemId) {
            object[] results = this.Invoke("CheckStatus", new object[] {
                        systemId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckStatus(int systemId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckStatus", new object[] {
                        systemId}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckStatusAsync(int systemId) {
            this.CheckStatusAsync(systemId, null);
        }
        
        /// <remarks/>
        public void CheckStatusAsync(int systemId, object userState) {
            if ((this.CheckStatusOperationCompleted == null)) {
                this.CheckStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckStatusOperationCompleted);
            }
            this.InvokeAsync("CheckStatus", new object[] {
                        systemId}, this.CheckStatusOperationCompleted, userState);
        }
        
        private void OnCheckStatusOperationCompleted(object arg) {
            if ((this.CheckStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckStatusCompleted(this, new CheckStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void AddQueueCompletedEventHandler(object sender, AddQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void CheckStatusCompletedEventHandler(object sender, CheckStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
