//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


namespace Bluesea
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CardPortBinding", Namespace = "http://card.bstc.com/")]
    public partial class Card : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CardChargeBlueSeaOperationCompleted;

        private System.Threading.SendOrPostCallback CardLogOperationCompleted;

        /// <remarks/>
        public Card(string url)
        {
            //this.Url = "http://sms.8x77.vn:8077/Card/Card";
            this.Url = url;
        }

        /// <remarks/>
        public event CardChargeBlueSeaCompletedEventHandler CardChargeBlueSeaCompleted;

        /// <remarks/>
        public event CardLogCompletedEventHandler CardLogCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CardChargeBluesea", RequestNamespace = "http://card.bstc.com/", ResponseNamespace = "http://card.bstc.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CardChargeBlueSea([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string nickname, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string card_serial, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string card_code, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string provider, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_code)
        {
            object[] results = this.Invoke("CardChargeBlueSea", new object[] {
                    nickname,
                    card_serial,
                    card_code,
                    provider,
                    merchant_code});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCardChargeBlueSea(string nickname, string card_serial, string card_code, string provider, string merchant_code, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CardChargeBlueSea", new object[] {
                    nickname,
                    card_serial,
                    card_code,
                    provider,
                    merchant_code}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCardChargeBlueSea(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CardChargeBlueSeaAsync(string nickname, string card_serial, string card_code, string provider, string merchant_code)
        {
            this.CardChargeBlueSeaAsync(nickname, card_serial, card_code, provider, merchant_code, null);
        }

        /// <remarks/>
        public void CardChargeBlueSeaAsync(string nickname, string card_serial, string card_code, string provider, string merchant_code, object userState)
        {
            if ((this.CardChargeBlueSeaOperationCompleted == null))
            {
                this.CardChargeBlueSeaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardChargeBlueSeaOperationCompleted);
            }
            this.InvokeAsync("CardChargeBlueSea", new object[] {
                    nickname,
                    card_serial,
                    card_code,
                    provider,
                    merchant_code}, this.CardChargeBlueSeaOperationCompleted, userState);
        }

        private void OnCardChargeBlueSeaOperationCompleted(object arg)
        {
            if ((this.CardChargeBlueSeaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardChargeBlueSeaCompleted(this, new CardChargeBlueSeaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CardLog", RequestNamespace = "http://card.bstc.com/", ResponseNamespace = "http://card.bstc.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CardLog([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string Merchant_Code, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string Merchant_Key, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string Card_Code, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string Card_Serial, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string From_Date, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string To_Date)
        {
            object[] results = this.Invoke("CardLog", new object[] {
                    Merchant_Code,
                    Merchant_Key,
                    Card_Code,
                    Card_Serial,
                    From_Date,
                    To_Date});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCardLog(string Merchant_Code, string Merchant_Key, string Card_Code, string Card_Serial, string From_Date, string To_Date, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CardLog", new object[] {
                    Merchant_Code,
                    Merchant_Key,
                    Card_Code,
                    Card_Serial,
                    From_Date,
                    To_Date}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCardLog(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CardLogAsync(string Merchant_Code, string Merchant_Key, string Card_Code, string Card_Serial, string From_Date, string To_Date)
        {
            this.CardLogAsync(Merchant_Code, Merchant_Key, Card_Code, Card_Serial, From_Date, To_Date, null);
        }

        /// <remarks/>
        public void CardLogAsync(string Merchant_Code, string Merchant_Key, string Card_Code, string Card_Serial, string From_Date, string To_Date, object userState)
        {
            if ((this.CardLogOperationCompleted == null))
            {
                this.CardLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardLogOperationCompleted);
            }
            this.InvokeAsync("CardLog", new object[] {
                    Merchant_Code,
                    Merchant_Key,
                    Card_Code,
                    Card_Serial,
                    From_Date,
                    To_Date}, this.CardLogOperationCompleted, userState);
        }

        private void OnCardLogOperationCompleted(object arg)
        {
            if ((this.CardLogCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardLogCompleted(this, new CardLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CardChargeBlueSeaCompletedEventHandler(object sender, CardChargeBlueSeaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardChargeBlueSeaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CardChargeBlueSeaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CardLogCompletedEventHandler(object sender, CardLogCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CardLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}