//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace APIMyVNTP.GSM
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GsmServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class GsmService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ClearOperationCompleted;

        private System.Threading.SendOrPostCallback ClearPortOperationCompleted;

        private System.Threading.SendOrPostCallback ClearAllOperationCompleted;

        private System.Threading.SendOrPostCallback DeviceResponseOperationCompleted;

        private System.Threading.SendOrPostCallback UssdRequestOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllPortInfoOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateSlotNumberOperationCompleted;

        private System.Threading.SendOrPostCallback GetDeviceInfoOperationCompleted;

        private System.Threading.SendOrPostCallback RequestSimNumberOperationCompleted;

        private System.Threading.SendOrPostCallback RequestSimBalanceOperationCompleted;

        private System.Threading.SendOrPostCallback IsReadyOperationCompleted;

        /// <remarks/>
        public GsmService(string url)
        {
            this.Url = url;
            // this.Url = "http://192.168.31.154:1580/gsmservice.asmx";
        }

        /// <remarks/>
        public event ClearCompletedEventHandler ClearCompleted;

        /// <remarks/>
        public event ClearPortCompletedEventHandler ClearPortCompleted;

        /// <remarks/>
        public event ClearAllCompletedEventHandler ClearAllCompleted;

        /// <remarks/>
        public event DeviceResponseCompletedEventHandler DeviceResponseCompleted;

        /// <remarks/>
        public event UssdRequestCompletedEventHandler UssdRequestCompleted;

        /// <remarks/>
        public event GetAllPortInfoCompletedEventHandler GetAllPortInfoCompleted;

        /// <remarks/>
        public event UpdateSlotNumberCompletedEventHandler UpdateSlotNumberCompleted;

        /// <remarks/>
        public event GetDeviceInfoCompletedEventHandler GetDeviceInfoCompleted;

        /// <remarks/>
        public event RequestSimNumberCompletedEventHandler RequestSimNumberCompleted;

        /// <remarks/>
        public event RequestSimBalanceCompletedEventHandler RequestSimBalanceCompleted;

        /// <remarks/>
        public event IsReadyCompletedEventHandler IsReadyCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Clear", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Clear(int portPos, int slotPos)
        {
            object[] results = this.Invoke("Clear", new object[] {
                        portPos,
                        slotPos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginClear(int portPos, int slotPos, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Clear", new object[] {
                        portPos,
                        slotPos}, callback, asyncState);
        }

        /// <remarks/>
        public string EndClear(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ClearAsync(int portPos, int slotPos)
        {
            this.ClearAsync(portPos, slotPos, null);
        }

        /// <remarks/>
        public void ClearAsync(int portPos, int slotPos, object userState)
        {
            if ((this.ClearOperationCompleted == null))
            {
                this.ClearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearOperationCompleted);
            }
            this.InvokeAsync("Clear", new object[] {
                        portPos,
                        slotPos}, this.ClearOperationCompleted, userState);
        }

        private void OnClearOperationCompleted(object arg)
        {
            if ((this.ClearCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearCompleted(this, new ClearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearPort", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ClearPort(int port)
        {
            object[] results = this.Invoke("ClearPort", new object[] {
                        port});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginClearPort(int port, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ClearPort", new object[] {
                        port}, callback, asyncState);
        }

        /// <remarks/>
        public string EndClearPort(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ClearPortAsync(int port)
        {
            this.ClearPortAsync(port, null);
        }

        /// <remarks/>
        public void ClearPortAsync(int port, object userState)
        {
            if ((this.ClearPortOperationCompleted == null))
            {
                this.ClearPortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearPortOperationCompleted);
            }
            this.InvokeAsync("ClearPort", new object[] {
                        port}, this.ClearPortOperationCompleted, userState);
        }

        private void OnClearPortOperationCompleted(object arg)
        {
            if ((this.ClearPortCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearPortCompleted(this, new ClearPortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearAll", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ClearAll()
        {
            object[] results = this.Invoke("ClearAll", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginClearAll(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ClearAll", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndClearAll(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ClearAllAsync()
        {
            this.ClearAllAsync(null);
        }

        /// <remarks/>
        public void ClearAllAsync(object userState)
        {
            if ((this.ClearAllOperationCompleted == null))
            {
                this.ClearAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearAllOperationCompleted);
            }
            this.InvokeAsync("ClearAll", new object[0], this.ClearAllOperationCompleted, userState);
        }

        private void OnClearAllOperationCompleted(object arg)
        {
            if ((this.ClearAllCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearAllCompleted(this, new ClearAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeviceResponse", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeviceResponse(string resp)
        {
            object[] results = this.Invoke("DeviceResponse", new object[] {
                        resp});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDeviceResponse(string resp, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DeviceResponse", new object[] {
                        resp}, callback, asyncState);
        }

        /// <remarks/>
        public string EndDeviceResponse(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void DeviceResponseAsync(string resp)
        {
            this.DeviceResponseAsync(resp, null);
        }

        /// <remarks/>
        public void DeviceResponseAsync(string resp, object userState)
        {
            if ((this.DeviceResponseOperationCompleted == null))
            {
                this.DeviceResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeviceResponseOperationCompleted);
            }
            this.InvokeAsync("DeviceResponse", new object[] {
                        resp}, this.DeviceResponseOperationCompleted, userState);
        }

        private void OnDeviceResponseOperationCompleted(object arg)
        {
            if ((this.DeviceResponseCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeviceResponseCompleted(this, new DeviceResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UssdRequest", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UssdRequest(string transId, string telco, string sim, string simTarget, string cardSerial, string cardCode, int actionType, string callbackUrl, int cardValue, int quota)
        {
            object[] results = this.Invoke("UssdRequest", new object[] {
                        transId,
                        telco,
                        sim,
                        simTarget,
                        cardSerial,
                        cardCode,
                        actionType,
                        callbackUrl,
                        cardValue,
                        quota});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUssdRequest(string transId, string telco, string sim, string simTarget, string cardSerial, string cardCode, int actionType, string callbackUrl, int cardValue, int quota, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UssdRequest", new object[] {
                        transId,
                        telco,
                        sim,
                        simTarget,
                        cardSerial,
                        cardCode,
                        actionType,
                        callbackUrl,
                        cardValue,
                        quota}, callback, asyncState);
        }

        /// <remarks/>
        public string EndUssdRequest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void UssdRequestAsync(string transId, string telco, string sim, string simTarget, string cardSerial, string cardCode, int actionType, string callbackUrl, int cardValue, int quota)
        {
            this.UssdRequestAsync(transId, telco, sim, simTarget, cardSerial, cardCode, actionType, callbackUrl, cardValue, quota, null);
        }

        /// <remarks/>
        public void UssdRequestAsync(string transId, string telco, string sim, string simTarget, string cardSerial, string cardCode, int actionType, string callbackUrl, int cardValue, int quota, object userState)
        {
            if ((this.UssdRequestOperationCompleted == null))
            {
                this.UssdRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUssdRequestOperationCompleted);
            }
            this.InvokeAsync("UssdRequest", new object[] {
                        transId,
                        telco,
                        sim,
                        simTarget,
                        cardSerial,
                        cardCode,
                        actionType,
                        callbackUrl,
                        cardValue,
                        quota}, this.UssdRequestOperationCompleted, userState);
        }

        private void OnUssdRequestOperationCompleted(object arg)
        {
            if ((this.UssdRequestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UssdRequestCompleted(this, new UssdRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPortInfo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllPortInfo()
        {
            object[] results = this.Invoke("GetAllPortInfo", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllPortInfo(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllPortInfo", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetAllPortInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetAllPortInfoAsync()
        {
            this.GetAllPortInfoAsync(null);
        }

        /// <remarks/>
        public void GetAllPortInfoAsync(object userState)
        {
            if ((this.GetAllPortInfoOperationCompleted == null))
            {
                this.GetAllPortInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPortInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllPortInfo", new object[0], this.GetAllPortInfoOperationCompleted, userState);
        }

        private void OnGetAllPortInfoOperationCompleted(object arg)
        {
            if ((this.GetAllPortInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPortInfoCompleted(this, new GetAllPortInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSlotNumber", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateSlotNumber(string number, int slotNo, int portNo)
        {
            object[] results = this.Invoke("UpdateSlotNumber", new object[] {
                        number,
                        slotNo,
                        portNo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdateSlotNumber(string number, int slotNo, int portNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateSlotNumber", new object[] {
                        number,
                        slotNo,
                        portNo}, callback, asyncState);
        }

        /// <remarks/>
        public string EndUpdateSlotNumber(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void UpdateSlotNumberAsync(string number, int slotNo, int portNo)
        {
            this.UpdateSlotNumberAsync(number, slotNo, portNo, null);
        }

        /// <remarks/>
        public void UpdateSlotNumberAsync(string number, int slotNo, int portNo, object userState)
        {
            if ((this.UpdateSlotNumberOperationCompleted == null))
            {
                this.UpdateSlotNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSlotNumberOperationCompleted);
            }
            this.InvokeAsync("UpdateSlotNumber", new object[] {
                        number,
                        slotNo,
                        portNo}, this.UpdateSlotNumberOperationCompleted, userState);
        }

        private void OnUpdateSlotNumberOperationCompleted(object arg)
        {
            if ((this.UpdateSlotNumberCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSlotNumberCompleted(this, new UpdateSlotNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeviceInfo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDeviceInfo()
        {
            object[] results = this.Invoke("GetDeviceInfo", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDeviceInfo(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDeviceInfo", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetDeviceInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetDeviceInfoAsync()
        {
            this.GetDeviceInfoAsync(null);
        }

        /// <remarks/>
        public void GetDeviceInfoAsync(object userState)
        {
            if ((this.GetDeviceInfoOperationCompleted == null))
            {
                this.GetDeviceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceInfoOperationCompleted);
            }
            this.InvokeAsync("GetDeviceInfo", new object[0], this.GetDeviceInfoOperationCompleted, userState);
        }

        private void OnGetDeviceInfoOperationCompleted(object arg)
        {
            if ((this.GetDeviceInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeviceInfoCompleted(this, new GetDeviceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestSimNumber", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestSimNumber(TelcoName telCo, int portNo)
        {
            object[] results = this.Invoke("RequestSimNumber", new object[] {
                        telCo,
                        portNo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestSimNumber(TelcoName telCo, int portNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestSimNumber", new object[] {
                        telCo,
                        portNo}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestSimNumber(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestSimNumberAsync(TelcoName telCo, int portNo)
        {
            this.RequestSimNumberAsync(telCo, portNo, null);
        }

        /// <remarks/>
        public void RequestSimNumberAsync(TelcoName telCo, int portNo, object userState)
        {
            if ((this.RequestSimNumberOperationCompleted == null))
            {
                this.RequestSimNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestSimNumberOperationCompleted);
            }
            this.InvokeAsync("RequestSimNumber", new object[] {
                        telCo,
                        portNo}, this.RequestSimNumberOperationCompleted, userState);
        }

        private void OnRequestSimNumberOperationCompleted(object arg)
        {
            if ((this.RequestSimNumberCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestSimNumberCompleted(this, new RequestSimNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestSimBalance", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestSimBalance(TelcoName telCo, bool prepaid, int portNo)
        {
            object[] results = this.Invoke("RequestSimBalance", new object[] {
                        telCo,
                        prepaid,
                        portNo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestSimBalance(TelcoName telCo, bool prepaid, int portNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestSimBalance", new object[] {
                        telCo,
                        prepaid,
                        portNo}, callback, asyncState);
        }

        /// <remarks/>
        public string EndRequestSimBalance(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void RequestSimBalanceAsync(TelcoName telCo, bool prepaid, int portNo)
        {
            this.RequestSimBalanceAsync(telCo, prepaid, portNo, null);
        }

        /// <remarks/>
        public void RequestSimBalanceAsync(TelcoName telCo, bool prepaid, int portNo, object userState)
        {
            if ((this.RequestSimBalanceOperationCompleted == null))
            {
                this.RequestSimBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestSimBalanceOperationCompleted);
            }
            this.InvokeAsync("RequestSimBalance", new object[] {
                        telCo,
                        prepaid,
                        portNo}, this.RequestSimBalanceOperationCompleted, userState);
        }

        private void OnRequestSimBalanceOperationCompleted(object arg)
        {
            if ((this.RequestSimBalanceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestSimBalanceCompleted(this, new RequestSimBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsReady", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsReady(string number)
        {
            object[] results = this.Invoke("IsReady", new object[] {
                        number});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIsReady(string number, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IsReady", new object[] {
                        number}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndIsReady(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void IsReadyAsync(string number)
        {
            this.IsReadyAsync(number, null);
        }

        /// <remarks/>
        public void IsReadyAsync(string number, object userState)
        {
            if ((this.IsReadyOperationCompleted == null))
            {
                this.IsReadyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsReadyOperationCompleted);
            }
            this.InvokeAsync("IsReady", new object[] {
                        number}, this.IsReadyOperationCompleted, userState);
        }

        private void OnIsReadyOperationCompleted(object arg)
        {
            if ((this.IsReadyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsReadyCompleted(this, new IsReadyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public enum TelcoName
    {

        /// <remarks/>
        VNP,

        /// <remarks/>
        VMS,

        /// <remarks/>
        VTT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void ClearCompletedEventHandler(object sender, ClearCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ClearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void ClearPortCompletedEventHandler(object sender, ClearPortCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearPortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ClearPortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void ClearAllCompletedEventHandler(object sender, ClearAllCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ClearAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void DeviceResponseCompletedEventHandler(object sender, DeviceResponseCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeviceResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void UssdRequestCompletedEventHandler(object sender, UssdRequestCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UssdRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UssdRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetAllPortInfoCompletedEventHandler(object sender, GetAllPortInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPortInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllPortInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void UpdateSlotNumberCompletedEventHandler(object sender, UpdateSlotNumberCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSlotNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateSlotNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetDeviceInfoCompletedEventHandler(object sender, GetDeviceInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeviceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDeviceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void RequestSimNumberCompletedEventHandler(object sender, RequestSimNumberCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestSimNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestSimNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void RequestSimBalanceCompletedEventHandler(object sender, RequestSimBalanceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestSimBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RequestSimBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void IsReadyCompletedEventHandler(object sender, IsReadyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsReadyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IsReadyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
