//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


namespace Libs.CardTelco.NganLuong
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "NGANLUONG_APIBinding", Namespace = "NS")]
    public partial class NGANLUONG_API : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CardChargeOperationCompleted;

        private System.Threading.SendOrPostCallback CardCharge_v2OperationCompleted;

        /// <remarks/>
        public NGANLUONG_API(string url)
        {
            //this.Url = "https://nganluong.vn:443/mobile_card_api.php";
            this.Url = url;
        }

        /// <remarks/>
        public event CardChargeCompletedEventHandler CardChargeCompleted;

        /// <remarks/>
        public event CardCharge_v2CompletedEventHandler CardCharge_v2Completed;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nganluong.vn/mobile_card_api.php/CardCharge", RequestNamespace = "NS", ResponseNamespace = "NS")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string CardCharge(string merchant_id, string checksum, string @params)
        {
            object[] results = this.Invoke("CardCharge", new object[] {
                    merchant_id,
                    checksum,
                    @params});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCardCharge(string merchant_id, string checksum, string @params, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CardCharge", new object[] {
                    merchant_id,
                    checksum,
                    @params}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCardCharge(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CardChargeAsync(string merchant_id, string checksum, string @params)
        {
            this.CardChargeAsync(merchant_id, checksum, @params, null);
        }

        /// <remarks/>
        public void CardChargeAsync(string merchant_id, string checksum, string @params, object userState)
        {
            if ((this.CardChargeOperationCompleted == null))
            {
                this.CardChargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardChargeOperationCompleted);
            }
            this.InvokeAsync("CardCharge", new object[] {
                    merchant_id,
                    checksum,
                    @params}, this.CardChargeOperationCompleted, userState);
        }

        private void OnCardChargeOperationCompleted(object arg)
        {
            if ((this.CardChargeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardChargeCompleted(this, new CardChargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://nganluong.vn/mobile_card_api.php/CardCharge_v2", RequestNamespace = "NS", ResponseNamespace = "NS")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string CardCharge_v2(string merchant_id, string checksum, string @params)
        {
            object[] results = this.Invoke("CardCharge_v2", new object[] {
                    merchant_id,
                    checksum,
                    @params});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCardCharge_v2(string merchant_id, string checksum, string @params, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CardCharge_v2", new object[] {
                    merchant_id,
                    checksum,
                    @params}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCardCharge_v2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CardCharge_v2Async(string merchant_id, string checksum, string @params)
        {
            this.CardCharge_v2Async(merchant_id, checksum, @params, null);
        }

        /// <remarks/>
        public void CardCharge_v2Async(string merchant_id, string checksum, string @params, object userState)
        {
            if ((this.CardCharge_v2OperationCompleted == null))
            {
                this.CardCharge_v2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardCharge_v2OperationCompleted);
            }
            this.InvokeAsync("CardCharge_v2", new object[] {
                    merchant_id,
                    checksum,
                    @params}, this.CardCharge_v2OperationCompleted, userState);
        }

        private void OnCardCharge_v2OperationCompleted(object arg)
        {
            if ((this.CardCharge_v2Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardCharge_v2Completed(this, new CardCharge_v2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CardChargeCompletedEventHandler(object sender, CardChargeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardChargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CardChargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CardCharge_v2CompletedEventHandler(object sender, CardCharge_v2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardCharge_v2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CardCharge_v2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}